openapi: 3.0.3
info:
  version: 5.13.0
  title: Pinterest REST API
  description: Pinterest's REST API
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: ad_accounts
  description: |-
    View analytical information about advertising.


    Note: If the current operation_user_account (defined by the access token)
    has access to another user's Ad Accounts via
    <a href='/docs/reference/business-access/'>Pinterest Business Access</a>,
    you can modify your request to use the current operation_user_account's
    permissions to those Ad Accounts by including the ad_account_id in the path
    parameters for the request (e.g. .../?ad_account_id=12345&...).
- name: ad_groups
  description: View, create or update ad groups.
- name: ads
  description: View, create or update ads.
- name: audience_insights
  description: View audience insights.
- name: audiences
  description: View, create, or update audiences.
- name: billing
  description: View, create, or update information related to billing.
- name: boards
  description: View, create, update, or delete information about boards.
- name: bulk
  description: Create, update, or download ads-related entities in bulk.
- name: campaigns
  description: View, create or update campaigns.
- name: catalogs
  description: Manage information about shopping product catalogs and items.
- name: conversion_events
  description: Submit conversion events via the Pinterest API.
- name: conversion_tags
  description: View, create, or update conversion tags.
- name: customer_lists
  description: View, create, or update customer lists.
- name: integrations
  description: View, create, or update commerce integrations.
- name: keywords
  description: View, create or update keywords.
- name: lead_ads
  description: View, create, or update lead ads.
- name: lead_forms
  description: View lead forms.
- name: leads_export
  description: Create and export leads information from lead ads.
- name: media
  description: Register and manage media uploads.
- name: oauth
  description: Generate and refresh OAuth access tokens.
- name: order_lines
  description: View order lines.
- name: pins
  description: View, create, update, or delete information about Pins.
- name: product_group_promotions
  description: View, create, update, or delete information about promoted product
    groups.
- name: product_groups
  description: View, create, update, or delete information about product groups.
- name: resources
  description: View metadata about available metrics and targeting options in the
    Pinterest API.
- name: search
  description: Search for Pins and boards owned by the current user.
- name: targeting_template
  description: View, create or update targeting templates.
- name: terms
  description: View related and suggested terms for ads targeting.
- name: terms_of_service
  description: View Advertising Terms Of Service.
- name: user_account
  description: View user accounts associated with a given access token.
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
paths:
  /ad_accounts:
    get:
      summary: List ad accounts
      description: |-
        Get a list of the ad_accounts that the "operation user_account" has access to.
        - This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>.
      tags:
      - ad_accounts
      operationId: ad_accounts/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
    post:
      summary: Create ad account
      description: |-
        Create a new ad account. Different ad accounts can support different currencies, payment methods, etc.
        An ad account is needed to create campaigns, ad groups, and ads; other accounts (your employees or partners) can be assigned business access and appropriate roles to access an ad account. <p/>
        You can set up up to 50 ad accounts per user. (The user must have a business account to create an ad account.) <p/>
        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/create-an-advertiser-account">Create an advertiser account</a>.
      tags:
      - ad_accounts
      operationId: ad_accounts/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
  /ad_accounts/{ad_account_id}:
    get:
      summary: Get ad account
      description: Get an ad account
      operationId: ad_accounts/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ad_groups:
    get:
      summary: List ad groups
      description: |-
        List ad groups based on provided campaign IDs or ad group IDs.(campaign_ids or ad_group_ids). <p/>
        <strong>Note:</strong><p/>
        Provide only campaign_id or ad_group_id. Do not provide both.
      operationId: ad_groups/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ad_groups
    post:
      summary: Create ad groups
      description: "Create multiple new ad groups. All ads in a given ad group will\
        \ have the same budget, bid, run dates, targeting, and placement (search,\
        \ browse, other). For more information, <a href=\"https://help.pinterest.com/en/business/article/campaign-structure\"\
        \ target=\"_blank\"> click here</a>.</p>\n<strong>Note:</strong>\n- 'bid_in_micro_currency'\
        \ and 'budget_in_micro_currency' should be expressed in microcurrency amounts\
        \ based on the currency field set in the advertiser's profile.<p/>\n<p>Microcurrency\
        \ is used to track very small transactions, based on the currency set in the\
        \ advertiser\u2019s profile.</p>\n<p>A microcurrency unit is 10^(-6) of the\
        \ standard unit of currency selected in the advertiser\u2019s profile.</p>\n\
        \ <p><strong>Equivalency equations</strong>, using dollars as an example currency:</p>\n\
        <ul>\n  <li>$1 = 1,000,000 microdollars</li>\n  <li>1 microdollar = $0.000001\
        \ </li>\n</ul>\n<p><strong>To convert between currency and microcurrency</strong>,\
        \ using dollars as an example currency:</p>\n<ul>\n  <li>To convert dollars\
        \ to microdollars, mutiply dollars by 1,000,000</li>\n  <li>To convert microdollars\
        \ to dollars, divide microdollars by 1,000,000</li>\n</ul>\n- Ad groups belong\
        \ to ad campaigns. Some types of campaigns (e.g. budget optimization) have\
        \ limits on the number of ad groups they can hold. If you exceed those limits,\
        \ you will get an error message.\n- Start and end time cannot be set for ad\
        \ groups that belong to CBO campaigns. Currently, campaigns with the following\
        \ objective types: TRAFFIC, AWARENESS, WEB_CONVERSIONS, and CATALOG_SALES\
        \ will default to CBO."
      operationId: ad_groups/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - ad_groups
    patch:
      summary: Update ad groups
      description: Update multiple existing ad groups.
      operationId: ad_groups/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_groups/analytics:
    get:
      summary: Get ad group analytics
      description: |-
        Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: ad_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_groups/targeting_analytics:
    get:
      summary: Get targeting analytics for ad groups
      description: |-
        Get targeting analytics for one or more ad groups.
        For the requested ad group(s) and metrics, the response will include the requested metric information
        (e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>
        - The token's user_account must either be the Owner of the specified ad account, or have one
        of the necessary roles granted to them via
        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: ad_groups_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_groups/audience_sizing:
    post:
      summary: Get audience sizing
      description: "Get potential audience size for an ad group with given targeting\
        \ criteria. \nPotential audience size estimates the number of people you may\
        \ be able to reach per month with your campaign. \nIt is based on historical\
        \ advertising data and the targeting criteria you select.\nIt does not guarantee\
        \ results or take into account factors such as bid, budget, schedule, seasonality\
        \ or product experiments."
      operationId: ad_groups/audience_sizing
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_groups/{ad_group_id}:
    get:
      summary: Get ad group
      description: |-
        Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will
        contain additional information from the Ad Review process.
        For more information about our policies and rejection reasons see the <a href="https://www.pinterest.com/_/_/policy/advertising-guidelines/"
        target="_blank">Pinterest advertising standards</a>.
      operationId: ad_groups/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_previews:
    post:
      summary: Create ad preview with pin or image
      description: |-
        Create an ad preview given an ad account ID and either an existing organic pin ID or the URL for an image to be used to create the Pin and the ad. <p/>
        If you are creating a preview from an existing Pin, that Pin must be promotable: that is, it must have a clickthrough link and meet other requirements. (See <a href="https://help.pinterest.com/en/business/article/promoted-pins-overview" target="_blank">Ads Overview</a>.) <p/>
        You can view the returned preview URL on a webpage or iframe for 7 days, after which the URL expires. Collection ads are not currently supported ad preview.
      tags:
      - ads
      operationId: ad_previews/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
  /ad_accounts/{ad_account_id}/ads:
    get:
      summary: List ads
      description: |-
        List ads that meet the filters provided:
          - Listed campaign ids or ad group ids or ad ids
          - Listed entity statuses <p/>
        If no filter is provided, all ads in the ad account are returned. <p/>
        <strong>Note:</strong><p/>
        Provide only campaign_id or ad_group_id or ad_id. Do not provide more than one type. <p/>
        Review status is provided for each ad; if review_status is REJECTED, the rejected_reasons field will contain additional information.
        For more, see <a href="https://policy.pinterest.com/en/advertising-guidelines">Pinterest advertising standards</a>.
      operationId: ads/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ads
    post:
      description: Create multiple new ads. Request must contain ad_group_id, creative_type,
        and the source Pin pin_id.
      operationId: ads/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      summary: Create ads
      tags:
      - ads
    patch:
      description: Update multiple existing ads
      operationId: ads/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      summary: Update ads
      tags:
      - ads
  /ad_accounts/{ad_account_id}/ads/analytics:
    get:
      summary: Get ad analytics
      description: |-
        Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: ads/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - ads
  /ad_accounts/{ad_account_id}/ads_credit/discounts:
    get:
      summary: Get ads credit discounts
      description: |-
        Returns the list of discounts applied to the account.

        <strong>This endpoint might not be available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: ads_credits_discounts/get
      security:
      - pinterest_oauth2:
        - ads:read
        - billing:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/ads_credit/redeem:
    post:
      summary: Redeem ad credits
      description: |-
        Redeem ads credit on behalf of the ad account id and apply it towards billing.

        <strong>This endpoint might not be available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      tags:
      - billing
      operationId: ads_credit/redeem
      security:
      - pinterest_oauth2:
        - ads:write
        - billing:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
  /ad_accounts/{ad_account_id}/ads/targeting_analytics:
    get:
      summary: Get targeting analytics for ads
      description: |-
        Get targeting analytics for one or more ads. For the requested ad(s) and metrics,
        the response will include the requested metric information (e.g. SPEND_IN_DOLLAR) for the requested target type
        (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>
        - The token's user_account must either be the Owner of the specified ad account, or have one
        of the necessary roles granted to them via
        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: ad_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - ads
  /ad_accounts/{ad_account_id}/ads/{ad_id}:
    get:
      summary: Get ad
      description: |-
        Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will
        contain additional information from the Ad Review process.
        For more information about our policies and rejection reasons see the <a href="https://www.pinterest.com/_/_/policy/advertising-guidelines/"
        target="_blank">Pinterest advertising standards</a>.
      operationId: ads/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ads
  /ad_accounts/{ad_account_id}/analytics:
    get:
      summary: Get ad account analytics
      description: |-
        Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time.
      operationId: ad_account/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/audience_insights:
    get:
      summary: Get audience insights
      description: |-
        Get Audience Insights for an ad account. The response will return insights for 3 types of audiences: the
        ad account's engaged audience on Pinterest, the ad account's total audience on Pinterest and Pinterest's
        total audience.<p/>
        <a href="https://help.pinterest.com/en/business/article/audience-insights" target="_blank">Learn more about Audience Insights</a>.
      operationId: audience_insights/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - audience_insights
  /ad_accounts/{ad_account_id}/audiences:
    get:
      summary: List audiences
      description: Get list of audiences for the ad account.
      operationId: audiences/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - audiences
    post:
      description: |-
        Create an audience you can use in targeting for specific ad groups. Targeting combines customer information with
        the ways users interact with Pinterest to help you reach specific groups of users; you can include or exclude
        specific audience_ids when you create an ad group. <p/>
        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/audience-targeting" target="_blank">Audience targeting</a>.
      operationId: audiences/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create audience
      tags:
      - audiences
  /ad_accounts/{ad_account_id}/audiences/{audience_id}:
    get:
      summary: Get audience
      description: Get a specific audience given the audience ID.
      operationId: audiences/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - audiences
    patch:
      summary: Update audience
      description: Update (edit or remove) an existing targeting audience.
      operationId: audiences/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - audiences
  /ad_accounts/{ad_account_id}/audiences/custom:
    post:
      summary: Create custom audience
      description: Create a custom audience and find the audiences you want your ads
        to reach.
      operationId: audiences/create_custom
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - audiences
  /ad_accounts/{ad_account_id}/bid_floor:
    post:
      description: "List bid floors for your campaign configuration. Bid floors are\
        \ given in microcurrency values based on the currency in the bid floor specification.\
        \ <p/>\n<p>Microcurrency is used to track very small transactions, based on\
        \ the currency set in the advertiser\u2019s profile.</p>\n<p>A microcurrency\
        \ unit is 10^(-6) of the standard unit of currency selected in the advertiser\u2019\
        \ s profile.</p>\n<p><strong>Equivalency equations</strong>, using dollars\
        \ as an example currency:</p>\n<ul>\n  <li>$1 = 1,000,000 microdollars</li>\n\
        \  <li>1 microdollar = $0.000001 </li>\n</ul>\n<p><strong>To convert between\
        \ currency and microcurrency</strong>, using dollars as an example currency:</p>\n\
        <ul>\n  <li>To convert dollars to microdollars, mutiply dollars by 1,000,000</li>\n\
        \  <li>To convert microdollars to dollars, divide microdollars by 1,000,000</li>\n\
        \ </ul>\nFor more on bid floors see <a class=\"reference external\" href=\"\
        https://help.pinterest.com/en/business/article/set-your-bid\"> Set your bid</a>."
      operationId: ad_groups_bid_floor/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      summary: Get bid floors
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/billing_profiles:
    get:
      summary: Get billing profiles
      description: |-
        Get billing profiles in the advertiser account.

        <strong>This endpoint might not be available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: billing_profiles/get
      security:
      - pinterest_oauth2:
        - ads:read
        - billing:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/bulk/download:
    post:
      summary: Get advertiser entities in bulk
      description: |-
        Create an asynchronous report that may include information on campaigns, ad groups, product groups, ads,
        and/or keywords; can filter by campaigns. Though the entities may be active, archived, or paused,
        only active entities will return data.
      operationId: bulk_download/create
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - bulk
  /ad_accounts/{ad_account_id}/bulk/upsert:
    post:
      description: |-
        Either create or update any combination of campaigns, ad groups, product groups, ads, or keywords.
        Note that this request will be processed asynchronously; the response will include a <code>request_id</code>
        that can be used to obtain the status of the request.
      operationId: bulk_upsert/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create/update ad entities in bulk
      tags:
      - bulk
  /ad_accounts/{ad_account_id}/bulk/{bulk_request_id}:
    get:
      description: |-
        Get the status of a bulk request by <code>request_id</code>, along with a download URL that will allow you to download the
        new or updated entity data (campaigns, ad groups, product groups, ads, or keywords).
      operationId: bulk_request/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Download advertiser entities in bulk
      tags:
      - bulk
  /ad_accounts/{ad_account_id}/campaigns:
    get:
      summary: List campaigns
      description: |-
        Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: campaigns/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - campaigns
    post:
      summary: Create campaigns
      description: "Create multiple new campaigns. Every campaign has its own campaign_id\
        \ and houses one or more ad groups, which contain one or more ads.\nFor more,\
        \ see <a href=\"https://help.pinterest.com/en/business/article/set-up-your-campaign/\"\
        >Set up your campaign</a>. <p/>\n<strong>Note:</strong>\n- The values for\
        \ 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based\
        \ on the currency field set in the advertiser's profile. (e.g. USD) <p/>\n\
        <p>Microcurrency is used to track very small transactions, based on the currency\
        \ set in the advertiser\u2019s profile.</p>\n<p>A microcurrency unit is 10^(-6)\
        \ of the standard unit of currency selected in the advertiser\u2019s profile.</p>\n\
        \ <p><strong>Equivalency equations</strong>, using dollars as an example currency:</p>\n\
        <ul>\n  <li>$1 = 1,000,000 microdollars</li>\n  <li>1 microdollar = $0.000001\
        \ </li>\n</ul>\n<p><strong>To convert between currency and microcurrency</strong>,\
        \ using dollars as an example currency:</p>\n<ul>\n  <li>To convert dollars\
        \ to microdollars, mutiply dollars by 1,000,000</li>\n  <li>To convert microdollars\
        \ to dollars, divide microdollars by 1,000,000</li>\n</ul>"
      tags:
      - campaigns
      operationId: campaigns/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
    patch:
      summary: Update campaigns
      description: "Update multiple ad campaigns based on campaign_ids. <p/>\n<strong>Note:</strong><p/>\n\
        \ - <p>The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency\
        \ amounts based on the currency field set in the advertiser's profile. (e.g.\
        \ USD) <p/>\n<p>Microcurrency is used to track very small transactions, based\
        \ on the currency set in the advertiser\u2019s profile.</p>\n<p>A microcurrency\
        \ unit is 10^(-6) of the standard unit of currency selected in the advertiser\u2019\
        \ s profile.</p>\n<p><strong>Equivalency equations</strong>, using dollars\
        \ as an example currency:</p>\n<ul>\n  <li>$1 = 1,000,000 microdollars</li>\n\
        \  <li>1 microdollar = $0.000001 </li>\n</ul>\n<p><strong>To convert between\
        \ currency and microcurrency</strong>, using dollars as an example currency:</p>\n\
        <ul>\n  <li>To convert dollars to microdollars, mutiply dollars by 1,000,000</li>\n\
        \  <li>To convert microdollars to dollars, divide microdollars by 1,000,000</li>\n\
        </ul>"
      tags:
      - campaigns
      operationId: campaigns/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
  /ad_accounts/{ad_account_id}/campaigns/analytics:
    get:
      summary: Get campaign analytics
      description: |-
        Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: campaigns/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - campaigns
  /ad_accounts/{ad_account_id}/campaigns/targeting_analytics:
    get:
      summary: Get targeting analytics for campaigns
      description: |-
        Get targeting analytics for one or more campaigns.
        For the requested account and metrics, the response will include the requested metric information
        (e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>
        - The token's user_account must either be the Owner of the specified ad account, or have one
        of the necessary roles granted to them via
        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: campaign_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - campaigns
  /ad_accounts/{ad_account_id}/campaigns/{campaign_id}:
    get:
      summary: Get campaign
      description: Get a specific campaign given the campaign ID.
      operationId: campaigns/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - campaigns
  /ad_accounts/{ad_account_id}/conversion_tags:
    get:
      summary: Get conversion tags
      description: List conversion tags associated with an ad account.
      operationId: conversion_tags/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - conversion_tags
      x-sandbox: disabled
    post:
      x-sandbox: disabled
      summary: Create conversion tag
      description: "Create a conversion tag, also known as <a href=\"https://help.pinterest.com/en/business/article/set-up-the-pinterest-tag\"\
        \ target=\"_blank\">Pinterest tag</a>, with the option to enable enhanced\
        \ match.<p/>\nThe Pinterest Tag tracks actions people take on the ad account\u2019\
        \ s website after they view the ad account's ad on Pinterest. The advertiser\
        \ needs to customize this tag to track conversions.<p/>\nFor more information,\
        \ see:<p/>\n<a class=\"reference external\" href=\"https://help.pinterest.com/en/business/article/set-up-the-pinterest-tag\"\
        >Set up the Pinterest tag</a><p/>\n<a class=\"reference external\" href=\"\
        https://developers.pinterest.com/docs/conversions/pinterest-tag/\">Pinterest\
        \ Tag</a><p/>\n<a class=\"reference external\" href=\"https://developers.pinterest.com/docs/conversions/enhanced-match/\"\
        >Enhanced match</a>"
      operationId: conversion_tags/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      tags:
      - conversion_tags
  /ad_accounts/{ad_account_id}/conversion_tags/ocpm_eligible:
    get:
      summary: Get Ocpm eligible conversion tags
      description: Get Ocpm eligible conversion tag events for an ad account.
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      operationId: ocpm_eligible_conversion_tags/get
      x-sandbox: disabled
      tags:
      - conversion_tags
  /ad_accounts/{ad_account_id}/conversion_tags/page_visit:
    get:
      summary: Get page visit conversion tags
      description: Get all page visit conversion tag events for an ad account.
      operationId: page_visit_conversion_tags/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - conversion_tags
  /ad_accounts/{ad_account_id}/conversion_tags/{conversion_tag_id}:
    get:
      x-sandbox: disabled
      summary: Get conversion tag
      description: Get information about an existing conversion tag.
      operationId: conversion_tags/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - conversion_tags
  /ad_accounts/{ad_account_id}/customer_lists:
    post:
      description: "<p>Create a customer list from your records(hashed or plain-text\
        \ email addresses, or hashed MAIDs or IDFAs).</p>\n<p>A customer list is one\
        \ of the four types of Pinterest audiences: for more information, see <a href=\"\
        https://help.pinterest.com/en/business/article/audience-targeting\" target=\"\
        _blank\">Audience targeting</a>\nor the <a href=\"/docs/ads/targeting/#Audiences\"\
        \ target=\"_blank\">Audiences</a> section of the ads management guide.<p/>\n\
        \ <p><b>Please review our <u><a href=\"https://help.pinterest.com/en/business/article/audience-targeting#section-13341\"\
        \ target=\"_blank\">requirements</a></u> for what type of information is allowed\
        \ when uploading a customer list.</b></p>\n<p>When you create a customer list,\
        \ the system scans the list for existing Pinterest accounts;\nthe list must\
        \ include at least 100 Pinterest accounts. Your original list will be deleted\
        \ when the matching process\nis complete. The filtered list \u2013 containing\
        \ only the Pinterest accounts that were included in your starting\nlist \u2013\
        \ is what will be used to create the audience.</p>\n<p>Note that once you\
        \ have created your customer list, you must convert it into an audience (of\
        \ the \u201C CUSTOMER_LIST\u201D type)\nusing the <a href=\"#operation/create_audience_handler\"\
        >create audience endpoint</a> before it can be used.</p>"
      operationId: customer_lists/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create customer lists
      tags:
      - customer_lists
    get:
      description: |-
        <p>Get a set of customer lists including id and name based on the filters provided.</p>
        <p>(Customer lists are a type of audience.) For more information, see
        <a href="https://help.pinterest.com/en/business/article/audience-targeting" target="_blank">Audience targeting</a>
         or the <a href="/docs/ads/targeting/#Audiences" target="_blank">Audiences</a>
        section of the ads management guide.</p>
      operationId: customer_lists/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Get customer lists
      tags:
      - customer_lists
  /ad_accounts/{ad_account_id}/customer_lists/{customer_list_id}:
    get:
      summary: Get customer list
      description: Gets a specific customer list given the customer list ID.
      operationId: customer_lists/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - customer_lists
    patch:
      description: "<p>Append or remove records to/from an existing customer list.\
        \ (A customer list is one of the four types of Pinterest audiences.)</p>\n\
        <p>When you add records to an existing customer list, the system scans the\
        \ additions for existing Pinterest\naccounts; those are the records that will\
        \ be added to your \u201CCUSTOMER_LIST\u201D audience. Your original list\
        \ of records\n to add will be deleted when the matching process is complete.</p>\n\
        <p>For more information, see <a href=\"https://help.pinterest.com/en/business/article/audience-targeting\"\
        \ target=\"_blank\">Audience targeting</a>\nor the <a href=\"/docs/ads/targeting/#Audiences\"\
        \ target=\"_blank\">Audiences</a>\nsection of the ads management guide.</p>"
      operationId: customer_lists/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Update customer list
      tags:
      - customer_lists
  /ad_accounts/{ad_account_id}/events:
    post:
      summary: Send conversions
      description: |-
        The Pinterest API offers advertisers a way to send Pinterest their conversion information (including web conversions, in-app conversions, or even offline conversions) based on their <code>ad_account_id</code>. The request body should be a JSON object.
        - This endpoint requires an <code>access_token</code> be generated through Ads Manager. Review the <a href="/docs/conversions/conversions/">Conversions Guide</a> for more details.
        - The token's <code>user_account</code> must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Audience, Campaign. (Note that the token can be used across multiple ad accounts under an user ID.)
        - This endpoint has a rate limit of 5,000 calls per minute per ad account.
        - If the merchant is submitting this information using both Pinterest conversion tags and the Pinterest API, Pinterest will remove duplicate information before reporting. (Note that events that took place offline cannot be deduplicated.)
      operationId: events/create
      tags:
      - conversion_events
      security:
      - pinterest_oauth2:
        - ads:write
      - conversion_token: []
      x-ratelimit-category: ads_conversions
      x-sandbox: disabled
  /ad_accounts/{ad_account_id}/insights/audiences:
    get:
      summary: Get audience insights scope and type
      description: Get the scope and type of available audiences, which along with
        a date, is an audience that has recently had an interaction (referred to here
        as a type) on pins. Interacted pins can belong to at least the most common
        **partner** or **Pinterest** scopes. This means that user interactions made
        on advertiser or partner pins will have the **partner** scope. You can also
        have user interactions performed in general on Pinterest with the **Pinterest**
        scope. In that case, you can then use the returned type and scope values together
        on requests to other endpoints to retrieve insight metrics for a desired audience.
      operationId: audience_insights_scope_and_type/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - audience_insights
  /ad_accounts/{ad_account_id}/keywords:
    get:
      summary: Get keywords
      description: |-
        <p>Get a list of keywords based on the filters provided. If no filter is provided, it will default to the ad_account_id filter, which means it will only return keywords that specifically have parent_id set to the ad_account_id. Note: Keywords can have ad_account_ids, campaign_ids, and ad_group_ids set as their parent_ids. Keywords created through Ads Manager will have their parent_id set to an ad_group_id, not ad_account_id.</p>
        <p>For more information, see <a target="_blank" href="https://help.pinterest.com/en/business/article/keyword-targeting">Keyword targeting</a>.</p>
        <p><b>Notes:</b></p> <ul style="list-style-type: square;"> <li>Advertisers and campaigns can only be assigned keywords with excluding ('_NEGATIVE').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For more information on match types, see <a target="_blank" href="/docs/ads/targeting/#Match%20type%20and%20targeting%20level">match type enums</a>.</p>
        <p><b>Returns:</b></p> <ul style="list-style-type: square;"> <li><p>A successful call returns an object containing an array of new keyword objects and an empty &quot;errors&quot; object array.</p></li> <li><p>An unsuccessful call returns an empty keywords array, and, instead, inserts the entire object with nulled/negated properties into the &quot;errors&quot; object array:</p> <pre class="last literal-block"> { "keywords": [], "errors": [ { "data": { "archived": null, "match_type": "EXAC[...]
      operationId: keywords/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - keywords
    post:
      summary: Create keywords
      description: |-
        <p>Create keywords for following entity types(advertiser, campaign, ad group or ad).</p> <p>For more information, see <a target="_blank" href="https://help.pinterest.com/en/business/article/keyword-targeting">Keyword targeting</a>.</p>
        <p><b>Notes:</b></p> <ul style="list-style-type: square;"> <li>Advertisers and campaigns can only be assigned keywords with excluding ('_NEGATIVE').</li> <li>All keyword match types are available for ad groups.</li> </ul> <p>For more information on match types, see <a  target="_blank" href="/docs/ads/targeting/#Match%20type%20and%20targeting%20level">match type enums</a>.</p>
        <p><b>Returns:</b></p> <ul style="list-style-type: square;"> <li><p>A successful call returns an object containing an array of new keyword objects and an empty &quot;errors&quot; object array.</p></li> <li><p>An unsuccessful call returns an empty keywords array, and, instead, inserts the entire object with nulled/negated properties into the &quot;errors&quot; object array:</p> <pre class="last literal-block"> { "keywords": [], "errors": [ { "data": { "archived": null, "match_type": "EXAC[...]
        <p><b>Rate limit</b>: <a href="/docs/redoc/#tag/Rate-Limits">WRITE</a>.</p>
      operationId: keywords/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - keywords
    patch:
      summary: Update keywords
      description: <p>Update one or more keywords' bid and archived fields.</p> <p>Archiving
        a keyword effectively deletes it - keywords no longer receive metrics and
        no longer visible within the parent entity's keywords list.</p>
      operationId: keywords/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - keywords
  /ad_accounts/{ad_account_id}/keywords/metrics:
    get:
      summary: Get country's keyword metrics
      description: |-
        See keyword metrics for a specified country, aggregated across all of Pinterest.
        (Definitions are available from the "Get delivery metrics definitions"
        <a href="/docs/api/v5/#operation/delivery_metrics/get">API endpoint</a>).
      operationId: country_keywords_metrics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - keywords
  /ad_accounts/{ad_account_id}/lead_forms:
    get:
      summary: Get lead forms
      description: |-
        <strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>

        Gets all Lead Forms associated with an ad account ID.

        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/lead-ads">Lead ads</a>.
      operationId: lead_forms/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - lead_forms
  /ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}:
    get:
      summary: Get lead form by id
      description: |-
        <strong>This feature is currently in beta and not available to all apps, if you're interested in joining the beta, please reach out to your Pinterest account manager.</strong>

        Gets a lead form given it's ID. It must also be associated with the provided ad account ID.

        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/lead-ads">Lead ads</a>.
      operationId: lead_form/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - lead_forms
  /ad_accounts/{ad_account_id}/lead_forms/{lead_form_id}/test:
    post:
      summary: Create lead form test data
      description: |-
        Create lead form test data based on the list of answers provided as part of the body.
        - List of answers should follow the questions creation order.

        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: lead_form_test/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - lead_forms
  /ad_accounts/{ad_account_id}/leads/subscriptions:
    post:
      summary: Create lead ads subscription
      description: "Create a lead ads webhook subscription.\nSubscriptions allow Pinterest\
        \ to deliver lead data from Ads Manager directly to the subscriber. Subscriptions\
        \ can exist for a specific lead form or at ad account level. \n- Only requests\
        \ for the OWNER or ADMIN of the ad_account will be allowed.\n- Advertisers\
        \ can set up multiple integrations using ad_account_id + lead_form_id but\
        \ only one integration per unique records.\n- For data security, egress lead\
        \ data is encrypted with AES-256-GCM.\n\n<strong>This endpoint is currently\
        \ in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn\
        \ more</a>.</strong>"
      tags:
      - lead_ads
      operationId: ad_accounts_subscriptions/post
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
    get:
      summary: Get lead ads subscriptions
      description: |-
        Get the advertiser's list of lead ads subscriptions.
        - Only requests for the OWNER or ADMIN of the ad_account will be allowed.

        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: ad_accounts_subscriptions/get_list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - lead_ads
  /ad_accounts/{ad_account_id}/leads/subscriptions/{subscription_id}:
    get:
      summary: Get lead ads subscription
      description: |-
        Get a specific lead ads subscription record.
        - Only requests for the OWNER or ADMIN of the ad_account will be allowed.

        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: ad_accounts_subscriptions/get_by_id
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - lead_ads
    delete:
      summary: Delete lead ads subscription
      description: |-
        Delete an existing lead ads webhook subscription by ID.
        - Only requests for the OWNER or ADMIN of the ad_account will be allowed.

        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: ad_accounts_subscriptions/del_by_id
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - lead_ads
  /ad_accounts/{ad_account_id}/mmm_reports:
    get:
      summary: Get advertiser Marketing Mix Modeling (MMM) report.
      description: |-
        Get an mmm report for an ad account. This returns a URL to an mmm metrics report given a token returned from the
        create mmm report endpoint.
      operationId: analytics/get_mmm_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - ad_accounts
    post:
      summary: Create a request for a Marketing Mix Modeling (MMM) report
      description: |-
        This creates an asynchronous mmm report based on the given request. It returns a token that you can use to download
        the report when it is ready. NOTE: An additional limit of 5 queries per minute per advertiser applies to this endpoint while it's in beta release.
      operationId: analytics/create_mmm_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/order_lines:
    get:
      summary: Get order lines
      description: List existing order lines associated with an ad account.
      operationId: order_lines/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - order_lines
  /ad_accounts/{ad_account_id}/order_lines/{order_line_id}:
    get:
      summary: Get order line
      description: Get a specific existing order line associated with an ad account.
      operationId: order_lines/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - order_lines
  /ad_accounts/{ad_account_id}/product_group_promotions:
    post:
      description: Add one or more product groups from your catalog to an existing
        ad group. (Product groups added to an ad group are a 'product group promotion.')
      operationId: product_group_promotions/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Create product group promotions
      tags:
      - product_group_promotions
    patch:
      description: Update multiple existing Product Group Promotions (by product_group_id)
      operationId: product_group_promotions/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Update product group promotions
      tags:
      - product_group_promotions
    get:
      description: |-
        List existing product group promotions associated with an ad account.

        Include either ad_group_id or product_group_promotion_ids in your request.

        <b>Note:</b> ad_group_ids and product_group_promotion_ids are mutually exclusive parameters.
        Only provide one. If multiple options are provided, product_group_promotion_ids takes precedence over ad_group_ids. If none are provided, the endpoint returns an error.
      operationId: product_group_promotions/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Get product group promotions
      tags:
      - product_group_promotions
  /ad_accounts/{ad_account_id}/product_group_promotions/{product_group_promotion_id}:
    get:
      description: Get a product group promotion by id
      operationId: product_group_promotions/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      summary: Get a product group promotion by id
      tags:
      - product_group_promotions
  /ad_accounts/{ad_account_id}/product_groups/analytics:
    get:
      summary: Get product group analytics
      description: |-
        Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: product_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - product_group_promotions
  /ad_accounts/{ad_account_id}/product_groups/catalogs:
    get:
      deprecated: true
      description: This endpoint is completely deprecated. Please use <a href='/docs/api/v5/#operation/catalogs_product_groups/list'>List
        product groups</a> from Catalogs API instead.
      operationId: ad_accounts_catalogs_product_groups/list
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      summary: Get catalog product groups
      tags:
      - product_groups
  /ad_accounts/{ad_account_id}/reports:
    get:
      summary: Get the account analytics report created by the async call
      description: |-
        This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report. The link is valid for five minutes and the report is valid for one hour.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: analytics/get_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - ad_accounts
    post:
      summary: Create async request for an account analytics report
      description: |-
        This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 914 days before the current date in UTC time and the max time range supported is 186 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
        - If level is PRODUCT_ITEM, the furthest back you can are allowed to pull data is 92 days before the current date in UTC time and the max time range supported is 31 days.
        - If level is PRODUCT_ITEM, ad_ids and ad_statuses parameters are not allowed. Any columns related to pin promotion and ad is not allowed either.
      operationId: analytics/create_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/sandbox:
    delete:
      summary: Delete ads data for ad account in API Sandbox
      description: "Delete an ad account and all the ads data associated with that\
        \ account. \nA string message is returned indicating the status of the delete\
        \ operation.\n\nNote: This endpoint is only allowed in the Pinterest API Sandbox\
        \ (https://api-sandbox.pinterest.com/v5). \nGo to https://developers.pinterest.com/docs/dev-tools/sandbox/\
        \ for more information."
      operationId: sandbox/delete
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ssio/accounts:
    get:
      summary: Get Salesforce account details including bill-to information.
      description: |-
        Get Salesforce account details including bill-to information to be used in insertion orders process for <code>ad_account_id</code>.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.
      operationId: ssio_accounts/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/ssio/insertion_orders:
    post:
      summary: Create insertion order through SSIO.
      description: |-
        Create insertion order through SSIO for <code>ad_account_id</code>.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.
      operationId: ssio_insertion_order/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - billing
    patch:
      summary: Edit insertion order through SSIO.
      description: |-
        Edit insertion order through SSIO for <code>ad_account_id</code>.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.
      operationId: ssio_insertion_order/edit
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/ssio/insertion_orders/status:
    get:
      summary: Get insertion order status by ad account id.
      description: |-
        Get insertion order status for account id <code>ad_account_id</code>.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.
      operationId: ssio_insertion_orders_status/get_by_ad_account
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/ssio/insertion_orders/{pin_order_id}/status:
    get:
      summary: Get insertion order status by pin order id.
      description: |-
        Get insertion order status for pin order id <code>pin_order_id</code>.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.
      operationId: ssio_insertion_orders_status/get_by_pin_order_id
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/ssio/order_lines:
    get:
      summary: Get Salesforce order lines by ad account id.
      description: |-
        Get Salesforce order lines for account id <code>ad_account_id</code>.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Finance, Campaign.
      operationId: ssio_order_lines/get_by_ad_account
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - billing
  /ad_accounts/{ad_account_id}/targeting_analytics:
    get:
      summary: Get targeting analytics for an ad account
      description: |-
        Get targeting analytics for an ad account.
        For the requested account and metrics, the response will include the requested metric information
        (e.g. SPEND_IN_DOLLAR) for the requested target type (e.g. "age_bucket") for applicable values (e.g. "45-49"). <p/>
        - The token's user_account must either be the Owner of the specified ad account, or have one
        of the necessary roles granted to them via
        <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
        - If granularity is not HOUR, the furthest back you can are allowed to pull data is 90 days before the current date in UTC time and the max time range supported is 90 days.
        - If granularity is HOUR, the furthest back you can are allowed to pull data is 8 days before the current date in UTC time and the max time range supported is 3 days.
      operationId: ad_account_targeting_analytics/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/targeting_templates:
    get:
      summary: List targeting templates
      description: Get a list of the targeting templates in the specified <code>ad_account_id</code>
      operationId: targeting_template/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - targeting_template
    post:
      summary: Create targeting templates
      description: |-
        <p>Targeting templates allow advertisers to save a set of targeting details including audience lists,
         keywords & interest, demographics, and placements to use more than once during the campaign creation process.</p>
         <p>Templates can be used to build out basic targeting criteria that you plan to use across campaigns and to reuse
          performance targeting from prior campaigns for new campaigns.</p>
      operationId: targeting_template/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - targeting_template
    patch:
      summary: Update targeting templates
      description: <p>Update the targeting template given advertiser ID and targeting
        template ID</p>
      operationId: targeting_template/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - targeting_template
  /ad_accounts/{ad_account_id}/templates:
    get:
      summary: List templates
      description: Gets all Templates associated with an ad account ID.
      operationId: templates/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/templates/{template_id}/reports:
    post:
      summary: Create async request for an analytics report using a template
      description: |-
        This takes a template ID and an optional custom timeframe and constructs an asynchronous report based on the
        template. It returns a token that you can use to download the report when it is ready.
      operationId: analytics/create_template_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: disabled
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/terms_of_service:
    get:
      description: Get the text of the terms of service and see whether the advertiser
        has accepted the terms of service.
      operationId: terms_of_service/get
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      summary: Get terms of service
      tags:
      - terms_of_service
  /boards:
    get:
      summary: List boards
      description: |-
        Get a list of the boards owned by the "operation user_account" + group boards where this account is a collaborator
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        Optional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.
        - If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) will be returned.
      tags:
      - boards
      operationId: boards/list
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    post:
      summary: Create board
      description: |-
        Create a board owned by the "operation user_account".
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}:
    get:
      summary: Get board
      description: |-
        Get a board owned by the operation user_account - or a group board that has been shared with this account.
        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/get
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    patch:
      summary: Update board
      description: |-
        Update a board owned by the "operating user_account".
        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
    delete:
      summary: Delete board
      description: |-
        Delete a board owned by the "operation user_account".
        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}/pins:
    get:
      summary: List Pins on board
      description: |-
        Get a list of the Pins on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /boards/{board_id}/sections:
    get:
      summary: List board sections
      description: |-
        Get a list of all board sections from a board owned by the "operation user_account" - or a group board that has been shared with this account.
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/list
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    post:
      summary: Create board section
      description: |-
        Create a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}/sections/{section_id}:
    patch:
      summary: Update board section
      description: |-
        Update a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
    delete:
      summary: Delete board section
      description: |-
        Delete a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /boards/{board_id}/sections/{section_id}/pins:
    get:
      summary: List Pins on board section
      description: |-
        Get a list of the Pins on a board section of a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /businesses/employers:
    get:
      summary: List business employers for user
      description: Get all of the viewing user's business employers.
      operationId: get/business_employers
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - business_access_relationships
  /businesses/invites:
    patch:
      summary: Accept or decline an invite/request
      description: Accept or decline invites or requests.
      operationId: respond_business_access_invites
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - business_access_invite
  /businesses/{business_id}/assets/{asset_id}/members:
    get:
      summary: Get members with access to asset
      description: Get all the members the requesting business has granted access
        to on the given asset.
      operationId: business_asset_members/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/assets/{asset_id}/partners:
    get:
      summary: Get partners with access to asset
      description: |-
        Get all the partners the requesting business has granted access to on the given asset.
        Note: If the asset has been shared with you, an empty array will be returned. This is because an asset shared with
        you cannot be shared with a different partner.
      operationId: business_asset_partners/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/invites/assets/access:
    post:
      summary: Update invite/request with an asset permission
      description: |-
        Assign asset permissions information to an existing invite/request. Can be used to:
        - Request access to a partner's asset. Note: This is only for when no existing partnership exists. If an existing
          partnership exists, use "Create a request to access an existing partner's assets" to request access to your
          partner's assets.
            - invite_type="PARTNER_REQUEST"
        - Invite a partner to access your business assets. Note: This is only for when there is no existing partnership.
          If there is an existing partnership, use "Assign/Update partner asset permissions" to assign a partner access to
          new assets.
            - invite_type="PARTNER_INVITE"
        - Invite a member to access your business assets. Note: This is only for when there is no existing membership.
          If there is an existing membership, use "Assign/Update member asset permissions" to assign a member access to new
          assets.
            - invite_type="MEMBER_INVITE"

        To learn more about permission levels, visit https://help.pinterest.com/en/business/article/business-manager-overview.
      operationId: create_asset_invites
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_invite
  /businesses/{business_id}/requests/assets/access:
    post:
      summary: Create a request to access an existing partner's assets.
      description: Create a request to access an existing partner's assets with the
        specified permissions. The request will be sent to the partner for approval.
        The assets that can be requested are ad accounts and profiles.
      operationId: asset_access_requests/create
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_invite
  /businesses/{business_id}/members:
    get:
      summary: Get business members
      description: |-
        Get all members of the specified business.
        The return response will include the member's business_role and assets they have access to if assets_summary=TRUE
      operationId: get/business_members
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_relationships
    patch:
      description: Update a member's business role within the business.
      summary: Update member's business role
      operationId: update/business_memberships
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_relationships
    delete:
      description: Terminate memberships between the specified members and your business.
      summary: Terminate business memberships
      operationId: delete_business_membership
      security:
      - pinterest_oauth2:
        - biz_access:read
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: enabled
      tags:
      - business_access_relationships
  /businesses/{business_id}/assets:
    get:
      summary: List business assets
      description: Get all the assets the requesting business has access to. This
        includes assets the business owns and assets the business has access to through
        partnerships.
      operationId: business_assets/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/members/{member_id}/assets:
    get:
      summary: Get assets assigned to a member
      description: |-
        Get assets on which you assigned asset permissions to the given member. Can be used to:
        - get all assets, regardless of asset type or
        - get assets of one asset type by using the asset_type query.
        The return response will include the permissions the member has to that asset and the asset type.
      operationId: business_member_assets/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/members/assets/access:
    patch:
      description: |
        Grant multiple members access to assets and/or update multiple member's exisiting permissions to an asset.
        Note: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be applicable to an asset of type AD_ACCOUNT. The permission level PROFILE_PUBLISHER is only available to an asset of the type PROFILE.
      summary: Assign/Update member asset permissions
      operationId: business_members_asset_access/update
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_assets
    delete:
      description: Terminate multiple members' access to an asset.
      summary: Delete member access to asset
      operationId: business_members_asset_access/delete
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/invites:
    get:
      summary: Get invites/requests
      description: Get the membership/partnership invites and/or requests for the
        authorized user.
      operationId: get/invites
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_invite
    post:
      summary: Create invites or requests
      description: |-
        Create batch invites or requests. Can create batch invites or requests as described below.
        - Invite members to join the business. This would required specifying the following:
            - invite_type="MEMBER_INVITE"
            - business_role="EMPLOYEE" OR business_role="BIZ_ADMIN" (To learn more about business roles, visit
            https://help.pinterest.com/en/business/article/profile-permissions-in-business-access.)
            - members
        - Invite partners to access your business assets. This would require specifying the following:
            - invite_type="PARTNER_INVITE"
            - business_role="PARTNER"
            - partners
        - Request to be a partner so you can access their assets. This would require specifying the following:
            - invite_type="PARTNER_REQUEST"
            - business_role="PARTNER"
            - partners
      operationId: create_membership_or_partnership_invites
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_invite
    delete:
      summary: Cancel invites/requests
      description: Cancel membership/partnership invites and/or requests.
      operationId: cancel_invites_or_requests
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_invite
  /businesses/{business_id}/partners/assets:
    patch:
      summary: Assign/Update partner asset permissions
      description: |-
        Grant multiple partners access to assets and/or update multiple partner's exisiting permissions to an asset.
        If your partner already had permissions on the asset, they will be overriden with the new permissions you assign to them.
        To learn more about permission levels, visit https://help.pinterest.com/en/business/article/business-manager-overview

        Note: Not all listed permissions are applicable to each asset type. For example, PROFILE_PUBLISHER would not be
        applicable to an asset of type AD_ACCOUNT. The permission level PROFILE_PUBLISHER is only available to an asset of
        the type PROFILE.
      operationId: update_partner_asset_access_handler_impl
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_assets
    delete:
      summary: Delete partner access to asset
      description: |-
        Terminate multiple partners' access to an asset. If
        - partner_type=INTERNAL: You will terminate a partner's asset access to your business assets.
        - partner_type=EXTERNAL: You will terminate your own access to your partner's business assets.
      operationId: delete_partner_asset_access_handler_impl
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/partners/{partner_id}/assets:
    get:
      summary: Get assets assigned to a partner or assets assigned by a partner
      description: |-
        Can be used to get the business assets your partner has granted you access to or the business assets you have
        granted your partner access to. If you specify:
        - partner_type=INTERNAL, you will retrieve your business assets that the partner has access to.
        - partner_type=EXTERNAL, you will retrieve the partner's business assets that the partner has granted you access to.
      operationId: business_partner_asset_access/get
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_assets
  /businesses/{business_id}/partners:
    get:
      summary: Get business partners
      description: |-
        Get all partners of the specified business.

        If the assets_summary=TRUE and:
        - partner_type=INTERNAL, the business assets returned are your business assets the partner has access to.
        - partner_type=EXTERNAL, the business assets returned are your partner's business assets the partner has granted you
          access to.
      operationId: get/business_partners
      security:
      - pinterest_oauth2:
        - biz_access:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - business_access_relationships
    delete:
      summary: Terminate business partnerships
      description: |-
        Terminate partnerships between the specified partners and your business.
        Note: You may only batch terminate partners of the same partner type.
      operationId: delete_business_partners
      security:
      - pinterest_oauth2:
        - biz_access:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - business_access_relationships
  /catalogs:
    get:
      x-ratelimit-category: catalogs_read
      summary: List catalogs
      description: |-
        Fetch catalogs owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/feeds:
    get:
      x-ratelimit-category: catalogs_read
      summary: List feeds
      description: |-
        Fetch feeds owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        For Retail partners, refer to <a href='https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs'>Before you get started with Catalogs</a>. For Hotel parterns, refer to <a href='/docs/shopping/catalog/'>Pinterest API for shopping</a>.
      operationId: feeds/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
    post:
      x-ratelimit-category: catalogs_write
      summary: Create feed
      description: |-
        Create a new feed owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Please, be aware that "default_country"
        and "default_locale" are not required in the spec for forward compatibility
        but for now the API will not accept requests without those fields.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        For Retail partners, refer to <a href='https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs'>Before you get started with Catalogs</a>. For Hotel parterns, refer to <a href='/docs/shopping/catalog/'>Pinterest API for shopping</a>.

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: feeds/create
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/feeds/{feed_id}:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get feed
      description: |-
        Get a single feed owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        For Retail partners, refer to <a href='https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs'>Before you get started with Catalogs</a>. For Hotel parterns, refer to <a href='/docs/shopping/catalog/'>Pinterest API for shopping</a>.
      operationId: feeds/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
    patch:
      x-ratelimit-category: catalogs_write
      summary: Update feed
      description: |-
        Update a feed owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        For Retail partners, refer to <a href='https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs'>Before you get started with Catalogs</a>. For Hotel parterns, refer to <a href='/docs/shopping/catalog/'>Pinterest API for shopping</a>.

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: feeds/update
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      x-sandbox: enabled
      tags:
      - catalogs
    delete:
      x-ratelimit-category: catalogs_write
      summary: Delete feed
      description: |-
        Delete a feed owned by the "operating user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        For Retail partners, refer to <a href='https://help.pinterest.com/en/business/article/before-you-get-started-with-catalogs'>Before you get started with Catalogs</a>. For Hotel parterns, refer to <a href='/docs/shopping/catalog/'>Pinterest API for shopping</a>.
      operationId: feeds/delete
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/feeds/{feed_id}/ingest:
    post:
      x-ratelimit-category: catalogs_write
      summary: Ingest items for a given feed
      description: |-
        Ingest items for a given feed owned by the "operation user_account".

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>

        Note: This endpoint is only allowed in the Pinterest API Sandbox (https://api-sandbox.pinterest.com/v5).
        Go to https://developers.pinterest.com/docs/dev-tools/sandbox/ for more information.
      operationId: feeds/ingest
      security:
      - pinterest_oauth2:
        - catalogs:write
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/feeds/{feed_id}/processing_results:
    get:
      x-ratelimit-category: catalogs_read
      summary: List processing results for a given feed
      description: |-
        Fetch a feed processing results owned by the "operation user_account". Please note that for now the bookmark parameter is not functional and only the first page will be available until it is implemented in some release in the near future.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: feed_processing_results/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/processing_results/{processing_result_id}/item_issues:
    get:
      x-ratelimit-category: catalogs_read
      summary: List item issues for a given processing result
      description: |-
        List item validation issues for a given feed processing result owned by the "operation user_account". Up to 20 random samples of affected items are returned for each error and warning code. Please note that for now query parameters 'item_numbers' and 'item_validation_issue' cannot be used simultaneously until it is implemented in some release in the future.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: items_issues/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/items:
    get:
      summary: Get catalogs items
      description: |-
        Get the items of the catalog owned by the "operation user_account". <a href="/docs/shopping/catalog/#Update%20items%20in%20batch" target="_blank">See detailed documentation here.</a>
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: items/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      x-sandbox: enabled
      tags:
      - catalogs
    post:
      summary: Get catalogs items (POST)
      description: |-
        Get the items of the catalog owned by the "operation user_account". <a href="/docs/shopping/catalog/#Update%20items%20in%20batch" target="_blank">See detailed documentation here.</a>
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: items/post
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/items/batch:
    post:
      summary: Operate on item batch
      description: |-
        This endpoint supports multiple operations on a set of one or more catalog items owned by the "operation user_account". <a href="/docs/shopping/catalog/#Update%20items%20in%20batch" target="_blank">See detailed documentation here.</a>
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: items_batch/post
      x-ratelimit-category: catalogs_write
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      tags:
      - catalogs
  /catalogs/items/batch/{batch_id}:
    get:
      summary: Get catalogs item batch status
      description: |-
        Get a single catalogs items batch owned by the "operating user_account". <a href="/docs/shopping/catalog/#Update%20items%20in%20batch" target="_blank">See detailed documentation here.</a>
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.
      operationId: items_batch/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/product_groups/multiple:
    delete:
      x-ratelimit-category: catalogs_write
      summary: Delete multiple product groups
      description: |-
        Delete product groups owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs_product_groups/delete_many
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - catalogs:write
      tags:
      - catalogs
    post:
      x-ratelimit-category: catalogs_write
      summary: Create multiple product group
      description: |-
        Create product group to use in Catalogs owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: catalogs_product_groups/create_many
      security:
      - pinterest_oauth2:
        - catalogs:write
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/product_groups:
    get:
      x-ratelimit-category: catalogs_read
      summary: List product groups
      description: |-
        Get a list of product groups for a given Catalogs Feed Id owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs_product_groups/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
    post:
      x-ratelimit-category: catalogs_write
      summary: Create single product group
      description: |-
        Create product group to use in Catalogs owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: catalogs_product_groups/create
      security:
      - pinterest_oauth2:
        - catalogs:write
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/product_groups/{product_group_id}:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get single product group
      description: |-
        Get a singe product group for a given Catalogs Product Group Id owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs_product_groups/get
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
    delete:
      x-ratelimit-category: catalogs_write
      summary: Delete single product group
      description: |-
        Delete a product group owned by the "operation user_account" from being in use in Catalogs.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs_product_groups/delete
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - catalogs:write
      tags:
      - catalogs
    patch:
      x-ratelimit-category: catalogs_write
      summary: Update single product group
      description: |-
        Update product group owned by the "operation user_account" to use in Catalogs.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        <a href='/docs/shopping/catalog/'>Learn more</a>

        Note: The catalog type of Creative Assets is only allowed in the <a href='https://api-sandbox.pinterest.com/v5'>Pinterest API Sandbox</a>.
        If access is required, please contact your partner manager.
      operationId: catalogs_product_groups/update
      x-sandbox: enabled
      security:
      - pinterest_oauth2:
        - catalogs:write
      tags:
      - catalogs
  /catalogs/product_groups/{product_group_id}/product_counts:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get product counts for a Product Group
      description: |-
        Get a product counts for a given Catalogs Product Group owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        Note: This endpoint only supports RETAIL catalog at the moment.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs_product_groups/product_counts_get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/product_groups/{product_group_id}/products:
    get:
      x-ratelimit-category: catalogs_read
      summary: List products for a Product Group
      description: |-
        Get a list of product pins for a given Catalogs Product Group Id owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        Note: This endpoint only supports RETAIL catalog at the moment.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: catalogs_product_group_pins/list
      security:
      - pinterest_oauth2:
        - boards:read
        - catalogs:read
        - pins:read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/products/get_by_product_group_filters:
    post:
      x-ratelimit-category: catalogs_read
      summary: List products for Product Group Filters
      description: |-
        List products Pins owned by the "operation user_account" that meet the criteria specified in the Catalogs Product Group Filter given in the request.
        - This endpoint has been implemented in POST to allow for complex filters. This specific POST endpoint is designed to be idempotent.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.

        Note: This endpoint only supports RETAIL catalog at the moment.

        <a href='/docs/shopping/catalog/'>Learn more</a>
      operationId: products_by_product_group_filter/list
      security:
      - pinterest_oauth2:
        - boards:read
        - catalogs:read
        - pins:read
      x-sandbox: enabled
      tags:
      - catalogs
  /catalogs/reports:
    post:
      summary: Build catalogs report
      description: |-
        Async request to create a report of the catalog owned by the "operation user_account". This endpoint generates a report upon receiving the first approved request of the day. Any following requests with identical parameters will yield the same report even if data has changed.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.
      operationId: reports/create
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      x-sandbox: disabled
      tags:
      - catalogs
    get:
      summary: Get catalogs report
      description: |-
        This returns a URL to a report given a token returned from <a href='/docs/api/v5/#operation/reports/create'>Build catalogs report</a>. You can use the URL to download the report.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.
      operationId: reports/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      x-sandbox: disabled
      tags:
      - catalogs
  /catalogs/reports/stats:
    get:
      summary: List report stats
      description: |-
        List aggregated numbers of issues for a catalog owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.
      operationId: reports/stats
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      x-sandbox: disabled
      tags:
      - catalogs
  /integrations/commerce:
    post:
      summary: Create commerce integration
      description: |-
        Create commerce integration metadata to link an external business ID with a Pinterest merchant & ad account.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      operationId: integrations_commerce/post
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - integrations
  /integrations/commerce/{external_business_id}:
    get:
      summary: Get commerce integration
      description: |-
        Get commerce integration metadata associated with the given external business ID.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      operationId: integrations_commerce/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - integrations
    patch:
      summary: Update commerce integration
      description: |-
        Update commerce integration metadata for the given external business ID.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      operationId: integrations_commerce/patch
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - integrations
    delete:
      summary: Delete commerce integration
      description: |-
        Delete commerce integration metadata for the given external business ID.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      operationId: integrations_commerce/del
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      x-sandbox: disabled
      tags:
      - integrations
  /integrations/logs:
    post:
      summary: Receives batched logs from integration applications.
      description: |-
        This endpoint receives batched logs from integration applications on partner platforms.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      tags:
      - integrations
      operationId: integrations_logs/post
      x-ratelimit-category: ads_write
      security:
      - pinterest_oauth2:
        - ads:write
      x-sandbox: enabled
  /integrations:
    get:
      summary: Get integration metadata list
      description: |-
        Get integration metadata list.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      operationId: integrations/get_list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - integrations
  /integrations/{id}:
    get:
      summary: Get integration metadata
      description: |-
        Get integration metadata by ID.
        Note: If you're interested in joining the beta, please reach out to your Pinterest account manager.
      operationId: integrations/get_by_id
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: disabled
      tags:
      - integrations
  /media:
    get:
      summary: List media uploads
      description: |-
        List media uploads filtered by given parameters.

        <strong><a href='/docs/content/content-creation/#Creating%20video%20Pins'>Learn more</a></strong> about video Pin creation.
      tags:
      - media
      operationId: media/list
      security:
      - pinterest_oauth2:
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    post:
      summary: Register media upload
      description: |-
        Register your intent to upload media

        The response includes all of the information needed to upload the media
        to Pinterest.

        To upload the media, make an HTTP POST request (using <tt>curl</tt>, for
        example) to <tt>upload_url</tt> using the <tt>Content-Type</tt> header
        value. Send the media file's contents as the request's <tt>file</tt>
        parameter and also include all of the parameters from
        <tt>upload_parameters</tt>.

        <strong><a href='/docs/content/content-creation/#Creating%20video%20Pins'>Learn more</a></strong> about video Pin creation.
      tags:
      - media
      operationId: media/create
      security:
      - pinterest_oauth2:
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /media/{media_id}:
    get:
      summary: Get media upload details
      description: |-
        Get details for a registered media upload, including its current status.

        <strong><a href='/docs/content/content-creation/#Creating%20video%20Pins'>Learn more</a></strong> about video Pin creation.
      tags:
      - media
      operationId: media/get
      security:
      - pinterest_oauth2:
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /oauth/token:
    post:
      summary: Generate OAuth access token
      description: |-
        Generate an OAuth access token by using an authorization code or a refresh token.

        IMPORTANT: You need to start the OAuth flow via www.pinterest.com/oauth before calling this endpoint (or have an existing refresh token).

        See <a href='/docs/getting-started/authentication/'>Authentication</a> for more.

        <strong>Parameter <i>refresh_on</i> and its corresponding response type <i>everlasting_refresh</i> are now available to all apps! Later this year, continuous refresh will become the default behavior (ie you will no longer need to send this parameter). <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      tags:
      - oauth
      operationId: oauth/token
      security:
      - basic: []
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /pins:
    get:
      summary: List Pins
      description: |-
        Get a list of the Pins owned by the "operation user_account".
          - By default, the "operation user_account" is the token user_account.
          - All Pins owned by the "operation user_account" are included, regardless of who owns the board they are on.
        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".

        Disclaimer: there are known performance issues when filtering by field <code>creative_type</code> and including protected pins. If your
        request is timing out in this scenario we encourage you to use <a href='/docs/api/v5/#operation/boards/list_pins'>GET List Pins on Board</a>.
      operationId: pins/list
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
      tags:
      - pins
    post:
      summary: Create Pin
      description: |-
        Create a Pin on a board or board section owned by the "operation user_account".

        Note: If the current "operation user_account" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).

        - This function is intended solely for publishing new content created by the user. If you are interested in saving content created by others to your Pinterest boards, sometimes called 'curated content', please use our <a href='/docs/add-ons/save-button'>Save button</a> instead. For more tips on creating fresh content for Pinterest, review our <a href='/docs/content/content-creation/'>Content App Solutions Guide</a>.

        <strong><a href='/docs/content/content-creation/#Creating%20video%20Pins'>Learn more</a></strong> about video Pin creation.
      tags:
      - pins
      operationId: pins/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /pins/{pin_id}:
    get:
      summary: Get Pin
      description: |-
        Get a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.
      tags:
      - pins
      operationId: pins/get
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
    delete:
      summary: Delete Pin
      description: |-
        Delete a Pins owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.
      tags:
      - pins
      operationId: pins/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
    patch:
      summary: Update Pin
      description: |-
        Update a pin owned by the "operating user_account".
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.

        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      tags:
      - pins
      operationId: pins/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /pins/{pin_id}/analytics:
    get:
      summary: Get Pin analytics
      description: |-
        Get analytics for a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href="https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list">List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Admin, Analyst.
        - For Pins on secret boards: Admin.

        If Pin was created before <code>2023-03-20</code> lifetime metrics will only be available for Video and Idea Pin formats. Lifetime metrics are available for all Pin formats since then.
      tags:
      - pins
      operationId: pins/analytics
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /pins/analytics:
    get:
      summary: Get multiple Pin analytics
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>

        Get analytics for multiple pins owned by the "operation user_account" - or on a group board that has been shared with this account.
        - The maximum number of pins supported in a single request is 100.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href="https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list">List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Admin, Analyst.
        - For Pins on secret boards: Admin.

        If Pin was created before <code>2023-03-20</code> lifetime metrics will only be available for Video and Idea Pin formats. Lifetime metrics are available for all Pin formats since then.
      tags:
      - pins
      operationId: multi_pins/analytics
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /pins/{pin_id}/save:
    post:
      summary: Save Pin
      description: |-
        Save a Pin on a board or board section owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.

        - Any Pin type can be saved: image Pin, video Pin, Idea Pin, product Pin, etc.
        - Any public Pin can be saved given a pin ID.
      tags:
      - pins
      operationId: pins/save
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /resources/ad_account_countries:
    get:
      summary: Get ad accounts countries
      description: Get Ad Accounts countries
      operationId: ad_account_countries/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - resources
  /resources/delivery_metrics:
    get:
      summary: Get available metrics' definitions
      description: |-
        Get the definitions for ads and organic metrics available across both synchronous and asynchronous report endpoints.
        The `display_name` attribute will match how the metric is named in our native tools like Ads Manager.
        See <a href='/docs/content/analytics/'>Organic Analytics</a> and <a href='/docs/ads/ad-analytics-reporting/'>Ads Analytics</a> for more information.
      operationId: delivery_metrics/get
      security:
      - pinterest_oauth2:
        - ads:read
        - pins:read
        - user_accounts:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - resources
  /resources/lead_form_questions:
    get:
      summary: Get lead form questions
      description: |-
        Get a list of all lead form question type names. Some questions might not be used.

        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>
      operationId: lead_form_questions/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - resources
  /resources/metrics_ready_state:
    get:
      summary: Get metrics ready state
      description: Learn whether conversion or non-conversion metrics are finalized
        and ready to query.
      operationId: metrics_ready_state/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      x-sandbox: enabled
      tags:
      - resources
  /resources/targeting/interests/{interest_id}:
    get:
      summary: Get interest details
      description: <p>Get details of a specific interest given interest ID.</p> <p>Click
        <a href="https://docs.google.com/spreadsheets/d/1HxL-0Z3p2fgxis9YBP2HWC3tvPrs1hAuHDRtH-NJTIM/edit#gid=118370875"
        target="_blank">here</a> for a spreadsheet listing interests and their IDs.</p>
      operationId: interest_targeting_options/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - resources
  /resources/targeting/{targeting_type}:
    get:
      summary: Get targeting options
      description: |-
        <p>You can use targeting values in ads placement to define your intended audience. </p> <p>Targeting metrics are organized around targeting specifications.</p> <p>For more information on ads targeting, see <a class="reference external" href="https://help.pinterest.com/en/business/article/audience-targeting" target="_blank">Audience targeting</a>.</p>
        <p><b>Sample return:</b></p> <pre class="literal-block"> [{&quot;36313&quot;: &quot;Australia: Moreton Bay - North&quot;, &quot;124735&quot;: &quot;Canada: North Battleford&quot;, &quot;36109&quot;: &quot;Australia: Murray&quot;, &quot;36108&quot;: &quot;Australia: Mid North Coast&quot;, &quot;36101&quot;: &quot;Australia: Capital Region&quot;, &quot;811&quot;: &quot;U.S.: Reno&quot;, &quot;36103&quot;: &quot;Australia: Central West&quot;, &quot;36102&quot;: &quot;Australia: Central Coas[...]
      operationId: targeting_options/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - resources
  /search/boards:
    get:
      summary: Search user's boards
      description: |-
        Search for boards for the "operation user_account". This includes boards of all board types.
        - By default, the "operation user_account" is the token user_account.

        If using Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account". See <a href='/docs/reference/business-access/'>Understanding Business Access</a> for more information.
      operationId: search_user_boards/get
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:read_secret
      x-ratelimit-category: org_read
      x-sandbox: disabled
      tags:
      - search
  /search/pins:
    get:
      description: |-
        Search for pins for the "operation user_account".
        - By default, the "operation user_account" is the token user_account.

        If using Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account". See <a href='/docs/reference/business-access/'>Understanding Business Access</a> for more information.
      operationId: search_user_pins/list
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:read_secret
        - pins:read
        - pins:read_secret
      x-ratelimit-category: org_read
      x-sandbox: disabled
      summary: Search user's Pins
      tags:
      - search
  /search/partner/pins:
    get:
      summary: Search pins by a given search term
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>

        Get the top 10 Pins by a given search term.
      operationId: search_partner_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
      tags:
      - search
  /terms/related:
    get:
      summary: List related terms
      description: |-
        Get a list of terms logically related to each input term. <p/>
        Example: the term 'workout' would list related terms like 'one song workout', 'yoga workout', 'workout motivation', etc.
      tags:
      - terms
      operationId: terms_related/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
  /terms/suggested:
    get:
      summary: List suggested terms
      description: |-
        Get popular search terms that begin with your input term. <p/>
        Example: 'sport' would return popular terms like 'sports bar' and 'sportswear', but not 'motor sports' since the phrase does not begin with the given term.
      tags:
      - terms
      operationId: terms_suggested/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
  /trends/keywords/{region}/top/{trend_type}:
    get:
      summary: List trending keywords
      description: |-
        <p>Get the top trending search keywords among the Pinterest user audience.</p>
        <p>Trending keywords can be used to inform ad targeting, budget strategy, and creative decisions about which products and Pins will resonate with your audience.</p>
        <p>Geographic, demographic and interest-based filters are available to narrow down to the top trends among a specific audience. Multiple trend types are supported that can be used to identify newly-popular, evergreen or seasonal keywords.</p>
        <p>For an interactive way to explore this data, please visit <a href="https://trends.pinterest.com">trends.pinterest.com</a>.
      operationId: trending_keywords/list
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: trends_read
      x-sandbox: enabled
      tags:
      - keywords
  /user_account:
    get:
      summary: Get user account
      description: |-
        Get account information for the "operation user_account"
        - By default, the "operation user_account" is the token user_account.

        If using Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account". See <a href='/docs/reference/business-access/'>Understanding Business Access</a> for more information.
      tags:
      - user_account
      operationId: user_account/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
  /user_account/analytics:
    get:
      summary: Get user account analytics
      description: |-
        Get analytics for the "operation user_account"
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /user_account/analytics/top_pins:
    get:
      summary: Get user account top pins analytics
      description: |-
        Gets analytics data about a user's top pins (limited to the top 50).
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics/top_pins
      security:
      - pinterest_oauth2:
        - pins:read
        - user_accounts:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /user_account/analytics/top_video_pins:
    get:
      summary: Get user account top video pins analytics
      description: |-
        Gets analytics data about a user's top video pins (limited to the top 50).
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics/top_video_pins
      security:
      - pinterest_oauth2:
        - pins:read
        - user_accounts:read
      x-ratelimit-category: org_analytics
      x-sandbox: disabled
  /user_account/businesses:
    get:
      summary: List linked businesses
      description: Get a list of your linked business accounts.
      operationId: linked_business_accounts/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
      tags:
      - user_account
  /user_account/followers:
    get:
      summary: List followers
      description: Get a list of your followers.
      operationId: followers/list
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: ads_read
      x-sandbox: enabled
      tags:
      - user_account
  /user_account/following:
    get:
      summary: List following
      description: Get a list of who a certain user follows.
      operationId: user_following/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
      tags:
      - user_account
  /user_account/following/boards:
    get:
      summary: List following boards
      description: Get a list of the boards a user follows. The request returns a
        board summary object array.
      operationId: boards_user_follows/list
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
      tags:
      - user_account
  /user_account/following/{username}:
    post:
      summary: Follow user
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/new/about-beta-access/'>Learn more</a>.</strong>

        Use this request, as a signed-in user, to follow another user.
      tags:
      - user_account
      operationId: follow_user/update
      security:
      - pinterest_oauth2:
        - user_accounts:write
      x-ratelimit-category: org_write
      x-sandbox: enabled
  /user_account/websites:
    post:
      summary: Verify website
      description: Verify a website as a signed-in user.
      tags:
      - user_account
      operationId: verify_website/update
      security:
      - pinterest_oauth2:
        - user_accounts:write
      x-ratelimit-category: org_write
      x-sandbox: disabled
    get:
      summary: Get user websites
      description: Get user websites, claimed or not
      tags:
      - user_account
      operationId: user_websites/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
    delete:
      summary: Unverify website
      description: Unverifu a website verified by the signed-in user.
      tags:
      - user_account
      operationId: unverify_website/delete
      security:
      - pinterest_oauth2:
        - user_accounts:write
      x-ratelimit-category: org_write
      x-sandbox: disabled
  /user_account/websites/verification:
    get:
      summary: Get user verification code for website claiming
      description: Get verification code for user to install on the website to claim
        it.
      tags:
      - user_account
      operationId: website_verification/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: disabled
  /users/{username}/interests/follow:
    get:
      summary: List following interests
      description: Get a list of a user's following interests in one place.
      tags:
      - user_account
      operationId: user_account/followed_interests
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
      x-sandbox: enabled
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups,
              campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles,
              etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint
        (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer
        token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic