openapi: 3.0.3
info:
  version: 5.1.0
  title: Pinterest REST API (Beta)
  description: Pinterest's REST API
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
    email: pinterest-api@pinterest.com
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: ad_accounts
  description: Interact with and view information about advertising.
- name: boards
  description: Interact with and view information about boards.
- name: media
  description: Register and manage media uploads.
- name: oauth
  description: Generating and refreshing OAuth access tokens
- name: pins
  description: Interact with and view information about Pins.
- name: user_account
  description: Read only information about user accounts associated with a given access
    token.
paths:
  /oauth/token:
    post:
      summary: Generate OAuth access token
      description: Generate an OAuth access token by using an authorization code or
        a refresh token.
      tags:
      - oauth
      operationId: oauth/token
      security:
      - {}
  /user_account:
    get:
      summary: Get user account
      description: |-
        Get account information for the "operation user_account"
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
  /user_account/analytics:
    get:
      summary: Get user account analytics
      description: |-
        Get analytics for the "operation user_account"
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics
      security:
      - pinterest_oauth2:
        - user_accounts:read
  /pins:
    post:
      summary: Create Pin
      description: "Create a Pin owned by the \"operation user_account\".\n- By default,\
        \ the \"operation user_account\" is the token user_account.\n\nNotes on the\
        \ `POST /pins` function:\n\n1. This function is designed to create static\
        \ Pins only - it is not currently possible to use this endpoint to create\
        \ video Pins or Idea Pins.\n2. This function is intended solely for publishing\
        \ new static content created by the user. If you are interested in saving\
        \ images created by others to your Pinterest boards, sometimes called \u2018\
        curated content\u2019, please use our <a href=\"https://developers.pinterest.com/docs/add-ons/save-button\"\
        >Save button</a> instead. For more tips on creating fresh content for Pinterest,\
        \ review our <a href=\"https://developers.pinterest.com/docs/solutions/content-apps\"\
        >Content App Solutions Guide</a>."
      tags:
      - pins
      operationId: pins/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
  /pins/{pin_id}:
    get:
      summary: Get Pin
      description: |-
        Get a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href="https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list">List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.
      tags:
      - pins
      operationId: pins/get
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
    delete:
      summary: Delete Pin
      description: |-
        Delete a Pins owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - pins
      operationId: pins/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
  /pins/{pin_id}/analytics:
    get:
      summary: Get Pin analytics
      description: |-
        Get analytics for a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href="https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list">List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.
      tags:
      - pins
      operationId: pins/analytics
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
  /boards:
    get:
      summary: List boards
      description: |-
        Get a list of the boards owned by the "operation user_account" + group boards where this account is a collaborator
        - By default, the "operation user_account" is the token user_account.

        Optional: Specify a privacy (from the types: public, protected, secret) to indicate which boards to return.
        - If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) will be returned.
      tags:
      - boards
      operationId: boards/list
      security:
      - pinterest_oauth2:
        - boards:read
    post:
      summary: Create board
      description: |-
        Create a board owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
  /boards/{board_id}:
    get:
      summary: Get board
      description: |-
        Get a board owned by the operation user_account - or a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/get
      security:
      - pinterest_oauth2:
        - boards:read
    patch:
      summary: Update board
      description: |-
        Update a board owned by the "operating user_account".
        - By default, the "operating user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
    delete:
      summary: Delete board
      description: |-
        Delete a board owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
  /boards/{board_id}/sections:
    get:
      summary: List board sections
      description: |-
        Get a list of all board sections from a board owned by the "operation user_account" - or a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/list
      security:
      - pinterest_oauth2:
        - boards:read
    post:
      summary: Create board section
      description: |-
        Create a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
  /boards/{board_id}/sections/{section_id}:
    patch:
      summary: Update board section
      description: |-
        Update a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
    delete:
      summary: Delete board section
      description: |-
        Delete a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
  /boards/{board_id}/sections/{section_id}/pins:
    get:
      summary: List Pins on board section
      description: |-
        Get a list of the Pins on a board section of a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
  /boards/{board_id}/pins:
    get:
      summary: List Pins on board
      description: |-
        Get a list of the Pins on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
  /media:
    get:
      summary: List media uploads
      description: List media uploads filtered by given parameters.
      tags:
      - media
      operationId: media/list
      security:
      - pinterest_oauth2:
        - pins:read
    post:
      summary: Register media upload
      description: Register your intent to upload media (image, video, carousel, etc.)
      tags:
      - media
      operationId: media/create
      security:
      - pinterest_oauth2:
        - pins:read
        - pins:write
  /ad_accounts:
    get:
      summary: List ad accounts
      description: |-
        Get a list of the ad_accounts that the "operation user_account" has access to.
        - This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>.
      tags:
      - ad_accounts
      operationId: ad_accounts/list
      security:
      - pinterest_oauth2:
        - ads:read
  /ad_accounts/{ad_account_id}/analytics:
    get:
      summary: Get ad account analytics
      description: |-
        Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ad_account/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/campaigns:
    get:
      summary: List campaigns
      description: |-
        Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: campaigns/list
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/campaigns/analytics:
    get:
      summary: Get campaign analytics
      description: |-
        Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: campaigns/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ad_groups:
    get:
      summary: List ad groups
      description: |-
        Get a list of the ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ad_groups/list
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ad_groups/analytics:
    get:
      summary: Get ad group analytics
      description: |-
        Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ad_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ads:
    get:
      summary: List ads
      description: |-
        Get a list of the ads in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ads/list
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ads/analytics:
    get:
      summary: Get ad analytics
      description: |-
        Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ads/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/product_groups/analytics:
    get:
      summary: Get product group analytics
      description: |-
        Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: product_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      tags:
      - ad_accounts
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts
    basic:
      type: http
      scheme: basic