openapi: 3.0.3
info:
  version: 5.4.1
  title: Pinterest REST API
  description: Pinterest's REST API
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
    email: pinterest-api@pinterest.com
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: ad_accounts
  description: |-
    View analytical information about advertising.


    Note: If the current operation_user_account (defined by the access token)
    has access to another user's Ad Accounts via
    <a href='/docs/api/v5/#tag/Understanding-business-access'>Pinterest Business Access</a>,
    you can modify your request to use the current operation_user_account's
    permissions to those Ad Accounts by including the ad_account_id in the path
    parameters for the request (e.g. .../?ad_account_id=12345&...).
- name: ad_groups
  description: View, create or update ad groups.
- name: ads
  description: View, create or update ads.
- name: boards
  description: View, create, update, or delete information about boards.
- name: campaigns
  description: View, create or update campaigns.
- name: catalogs
  description: Manage information about shopping product catalogs and items.
- name: media
  description: Register and manage media uploads.
- name: oauth
  description: Generating and refreshing OAuth access tokens.
- name: pins
  description: View, create, update, or delete information about Pins.
- name: product_group_promotions
  description: Product Group Promotion
- name: terms
  description: Get related and suggested terms.
- name: terms_of_service
  description: Get Terms Of Service
- name: user_account
  description: Read-only information about user accounts associated with a given access
    token.
paths:
  /oauth/token:
    post:
      summary: Generate OAuth access token
      description: |-
        Generate an OAuth access token by using an authorization code or a refresh token.

        See <a href='/docs/api/v5/#tag/Authentication'>Authentication</a> for more.
      tags:
      - oauth
      operationId: oauth/token
      security:
      - {}
      x-ratelimit-category: org_read
  /user_account:
    get:
      summary: Get user account
      description: |-
        Get account information for the "operation user_account"
        - By default, the "operation user_account" is the token user_account.

        If using Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account". See <a href='/docs/api/v5/#tag/Understanding-business-access'>Understanding Business Access</a> for more information.
      tags:
      - user_account
      operationId: user_account/get
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_read
  /user_account/analytics:
    get:
      summary: Get user account analytics
      description: |-
        Get analytics for the "operation user_account"
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics
      security:
      - pinterest_oauth2:
        - user_accounts:read
      x-ratelimit-category: org_analytics
  /user_account/analytics/top_pins:
    get:
      summary: Get user account top pins analytics
      description: |-
        Gets analytics data about a user's top pins (limited to the top 50).
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics/top_pins
      security:
      - pinterest_oauth2:
        - pins:read
        - user_accounts:read
      x-ratelimit-category: org_analytics
  /user_account/analytics/top_video_pins:
    get:
      summary: Get user account top video pins analytics
      description: |-
        Gets analytics data about a user's top video pins (limited to the top 50).
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the "operation user_account".
      tags:
      - user_account
      operationId: user_account/analytics/top_video_pins
      security:
      - pinterest_oauth2:
        - pins:read
        - user_accounts:read
      x-ratelimit-category: org_analytics
  /pins:
    post:
      summary: Create Pin
      description: |-
        Create a Pin on a board or board section owned by the "operation user_account".

        Note: If the current "operation user_account" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).

        - This function is intended solely for publishing new content created by the user. If you are interested in saving content created by others to your Pinterest boards, sometimes called 'curated content', please use our <a href='/docs/add-ons/save-button'>Save button</a> instead. For more tips on creating fresh content for Pinterest, review our <a href='/docs/solutions/content-apps'>Content App Solutions Guide</a>.

        <strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.
      tags:
      - pins
      operationId: pins/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
  /pins/{pin_id}:
    get:
      summary: Get Pin
      description: |-
        Get a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Owner, Admin, Analyst, Campaign Manager.
        - For Pins on secret boards: Owner, Admin.
      tags:
      - pins
      operationId: pins/get
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
    delete:
      summary: Delete Pin
      description: |-
        Delete a Pins owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - pins
      operationId: pins/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
  /pins/{pin_id}/analytics:
    get:
      summary: Get Pin analytics
      description: |-
        Get analytics for a Pin owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.

        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href="https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list">List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account:

        - For Pins on public or protected boards: Admin, Analyst.
        - For Pins on secret boards: Admin.
      tags:
      - pins
      operationId: pins/analytics
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_analytics
  /boards:
    get:
      summary: List boards
      description: |-
        Get a list of the boards owned by the "operation user_account" + group boards where this account is a collaborator

        Optional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.
        - If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) will be returned.
      tags:
      - boards
      operationId: boards/list
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
    post:
      summary: Create board
      description: |-
        Create a board owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
  /boards/{board_id}:
    get:
      summary: Get board
      description: |-
        Get a board owned by the operation user_account - or a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/get
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
    patch:
      summary: Update board
      description: Update a board owned by the "operating user_account".
      tags:
      - boards
      operationId: boards/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
    delete:
      summary: Delete board
      description: |-
        Delete a board owned by the "operation user_account".
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
  /boards/{board_id}/sections:
    get:
      summary: List board sections
      description: |-
        Get a list of all board sections from a board owned by the "operation user_account" - or a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/list
      security:
      - pinterest_oauth2:
        - boards:read
      x-ratelimit-category: org_read
    post:
      summary: Create board section
      description: |-
        Create a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/create
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
  /boards/{board_id}/sections/{section_id}:
    patch:
      summary: Update board section
      description: |-
        Update a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/update
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
    delete:
      summary: Delete board section
      description: |-
        Delete a board section on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/delete
      security:
      - pinterest_oauth2:
        - boards:read
        - boards:write
      x-ratelimit-category: org_write
  /boards/{board_id}/sections/{section_id}/pins:
    get:
      summary: List Pins on board section
      description: |-
        Get a list of the Pins on a board section of a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: board_sections/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
  /boards/{board_id}/pins:
    get:
      summary: List Pins on board
      description: |-
        Get a list of the Pins on a board owned by the "operation user_account" - or on a group board that has been shared with this account.
        - By default, the "operation user_account" is the token user_account.
      tags:
      - boards
      operationId: boards/list_pins
      security:
      - pinterest_oauth2:
        - boards:read
        - pins:read
      x-ratelimit-category: org_read
  /media:
    get:
      summary: List media uploads
      description: |-
        List media uploads filtered by given parameters.

        <strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.
      tags:
      - media
      operationId: media/list
      security:
      - pinterest_oauth2:
        - pins:read
      x-ratelimit-category: org_read
    post:
      summary: Register media upload
      description: |-
        Register your intent to upload media

        The response includes all of the information needed to upload the media
        to Pinterest.

        To upload the media, make an HTTP POST request (using <tt>curl</tt>, for
        example) to <tt>upload_url</tt> using the <tt>Content-Type</tt> header
        value. Send the media file's contents as the request's <tt>file</tt>
        parameter and also include all of the parameters from
        <tt>upload_parameters</tt>.

        <strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.
      tags:
      - media
      operationId: media/create
      security:
      - pinterest_oauth2:
        - pins:read
        - pins:write
      x-ratelimit-category: org_write
  /media/{media_id}:
    get:
      summary: Get media upload details
      description: |-
        Get details for a registered media upload, including its current status.

        <strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.
      tags:
      - media
      operationId: media/get
      security:
      - pinterest_oauth2:
        - pins:read
      x-ratelimit-category: org_read
  /ad_accounts:
    get:
      summary: List ad accounts
      description: |-
        Get a list of the ad_accounts that the "operation user_account" has access to.
        - This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>.
      tags:
      - ad_accounts
      operationId: ad_accounts/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
    post:
      summary: Create ad account
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Create a new ad account. Different ad accounts can support different currencies, payment methods, etc.
        An ad account is needed to create campaigns, ad groups, and ads; other accounts (your employees or partners) can be assigned business access and appropriate roles to access an ad account. <p/>
        You can set up up to 50 ad accounts per user. (The user must have a business account to create an ad account.) <p/>
        For more, see <a class="reference external" href="https://help.pinterest.com/en/business/article/create-an-advertiser-account">Create an advertiser account</a>.
      tags:
      - ad_accounts
      operationId: ad_accounts/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
  /ad_accounts/{ad_account_id}:
    get:
      summary: Get ad account
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get an ad account
      operationId: ad_accounts/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/analytics:
    get:
      summary: Get ad account analytics
      description: |-
        Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ad_account/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/campaigns:
    get:
      summary: List campaigns
      description: |-
        Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: campaigns/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - campaigns
    post:
      summary: Create campaigns
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Create multiple new campaigns. Every campaign has its own campaign_id and houses one or more ad groups, which contain one or more ads.
        For more, see <a href="https://help.pinterest.com/en/business/article/set-up-your-campaign/">Set up your campaign</a>. <p/>
        <strong>Note:</strong>
        - The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>
        Microcurrency is used to track very small transactions, based on the currency field set in the advertiser's profile.
        A microcurrency unit is one one-millionth of the standard unit of currency selected in the advertiser's profile (e.g. a microdollar is $0.000001.)
      tags:
      - campaigns
      operationId: campaigns/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
    patch:
      summary: Update campaigns
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Update multiple ad campaigns based on campaign_ids. <p/>
        <strong>Note:</strong><p/>
        - The values for 'lifetime_spend_cap' and 'daily_spend_cap' are microcurrency amounts based on the currency field set in the advertiser's profile. (e.g. USD) <p/>
        Microcurrency is used to track very small transactions, based on the currency field set in the advertiser's profile.
        A microcurrency unit is one one-millionth of the standard unit of currency selected in the advertiser's profile (e.g. a microdollar is $0.000001.)
      tags:
      - campaigns
      operationId: campaigns/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
  /ad_accounts/{ad_account_id}/campaigns/{campaign_id}:
    get:
      summary: Get campaign
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get a specific campaign given the campaign ID.
      operationId: campaigns/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - campaigns
  /ad_accounts/{ad_account_id}/campaigns/analytics:
    get:
      summary: Get campaign analytics
      description: |-
        Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: campaigns/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ad_groups:
    get:
      summary: List ad groups
      description: |-
        List ad groups based on provided campaign IDs or ad group IDs.(campaign_ids or ad_group_ids). <p/>
        <strong>Note:</strong><p/>
        Provide only campaign_id or ad_group_id. Do not provide both.
      operationId: ad_groups/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - ad_groups
    post:
      summary: Create ad groups
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Create multiple new ad groups. All ads in a given ad group will have the same budget, bid, run dates, targeting, and placement (search, browse, other). For more information, <a href="https://help.pinterest.com/en/business/article/campaign-structure" target="_blank"> click here</a>.</p>
        <strong>Note:</strong>
        - 'bid_in_micro_currency' and 'budget_in_micro_currency' should be expressed in microcurrency amounts based on the currency field set in the advertiser's profile.
        Microcurrency is used to track very small transactions, based on the currency field set in the advertiser's profile.
        A microcurrency unit is one one-millionth of the standard unit of currency selected in the advertiser's profile (e.g. a microdollar is $0.000001.)
        - Ad groups belong to ad campaigns. Some types of campaigns (e.g. budget optimization) have limits on the number of ad groups they can hold. If you exceed those limits, you will get an error message.
      operationId: ad_groups/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      tags:
      - ad_groups
    patch:
      summary: Update ad groups
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Update multiple existing ad groups.
      operationId: ad_groups/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_groups/{ad_group_id}:
    get:
      summary: Get ad group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will
        contain additional information from the Ad Review process.
        For more information about our policies and rejection reasons see the <a href="https://www.pinterest.com/_/_/policy/advertising-guidelines/"
        target="_blank">Pinterest advertising standards</a>.
      operationId: ad_groups/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/ad_groups/analytics:
    get:
      summary: Get ad group analytics
      description: |-
        Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ad_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ads:
    get:
      summary: List ads
      description: |-
        List ads that meet the filters provided:
          - Listed campaign ids or ad group ids or ad ids
          - Listed entity statuses <p/>
        If no filter is provided, all ads in the ad account are returned. <p/>
        <strong>Note:</strong><p/>
        Provide only campaign_id or ad_group_id or ad_id. Do not provide more than one type. <p/>
        Review status is provided for each ad; if review_status is REJECTED, the rejected_reasons field will contain additional information.
        For more, see <a href="https://policy.pinterest.com/en/advertising-guidelines">Pinterest advertising standards</a>.
      operationId: ads/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - ads
    post:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Create multiple new ads. Request must contain ad_group_id, creative_type, and the source Pin pin_id.
      operationId: ads/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      summary: Create ads
      tags:
      - ads
    patch:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Update multiple existing ads
      operationId: ads/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      summary: Update ads
      tags:
      - ads
  /ad_accounts/{ad_account_id}/ads/{ad_id}:
    get:
      summary: Get ad
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get a specific ad given the ad ID. If your pin is rejected, rejected_reasons will
        contain additional information from the Ad Review process.
        For more information about our policies and rejection reasons see the <a href="https://www.pinterest.com/_/_/policy/advertising-guidelines/"
        target="_blank">Pinterest advertising standards</a>.
      operationId: ads/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      tags:
      - ads
  /ad_accounts/{ad_account_id}/ads/analytics:
    get:
      summary: Get ad analytics
      description: |-
        Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: ads/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/ad_previews:
    post:
      summary: Create ad preview with pin or image
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Create an ad preview given an ad account ID and either an existing organic pin ID or the URL for an image to be used to create the Pin and the ad. <p/>
        If you are creating a preview from an existing Pin, that Pin must be promotable: that is, it must have a clickthrough link and meet other requirements. (See <a href="https://help.pinterest.com/en/business/article/promoted-pins-overview" target="_blank">Ads Overview</a>.) <p/>
        You can view the returned preview URL on a webpage or iframe for 7 days, after which the URL expires.
      tags:
      - ads
      operationId: ad_previews/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
  /ad_accounts/{ad_account_id}/bid_floor:
    post:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        List bid floors for your campaign configuration. Bid floors are given in microcurrency values based on the currency in the bid floor specification. <p/>
        Microcurrency is used to track very small transactions, based on the currency field set in the advertiser's profile. A microcurrency unit is one one-millionth of the standard unit of currency selected in the advertiser's profile (e.g. a microdollar is $0.000001.) <p/>
        For more on bid floors see <a class="reference external" href="https://help.pinterest.com/en/business/article/set-your-bid"> Set your bid</a>.
      operationId: ad_groups_bid_floor/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      summary: Get bid floors
      tags:
      - ad_groups
  /ad_accounts/{ad_account_id}/product_groups/analytics:
    get:
      summary: Get product group analytics
      description: |-
        Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: product_groups/analytics
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/reports:
    get:
      summary: Get the account analytics report created by the async call
      description: |-
        This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report and it's valid for an hour.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: analytics/get_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
    post:
      summary: Create async request for an account analytics report
      description: |-
        This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.
        - The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a>: Admin, Analyst, Campaign Manager.
      operationId: analytics/create_report
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_analytics
      tags:
      - ad_accounts
  /ad_accounts/{ad_account_id}/product_group_promotions:
    post:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Add one or more product groups from your catalog to an existing ad group. (Product groups added to an ad group are a 'product group promotion.')
      operationId: product_group_promotions/create
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      summary: Create product group promotions
      tags:
      - product_group_promotions
    patch:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Update multiple existing Product Group Promotions (by product_group_id)
      operationId: product_group_promotions/update
      security:
      - pinterest_oauth2:
        - ads:write
      x-ratelimit-category: ads_write
      summary: Update product group promotions
      tags:
      - product_group_promotions
  /ad_accounts/{ad_account_id}/product_group_promotions/{product_group_promotion_id}:
    get:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get a product group promotion by id
      operationId: product_group_promotion/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      summary: Get a product group promotion by id
      tags:
      - product_group_promotions
  /terms/suggested:
    get:
      summary: List suggested terms
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get popular search terms that begin with your input term. <p/>
        Example: 'sport' would return popular terms like 'sports bar' and 'sportswear', but not 'motor sports' since the phrase does not begin with the given term.
      tags:
      - terms
      operationId: terms_suggested/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
  /ad_accounts/{ad_account_id}/terms_of_service:
    get:
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get the text of the terms of service and see whether the advertiser has accepted the terms of service.
      operationId: terms_of_service/get
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
      summary: Get terms of service
      tags:
      - terms_of_service
  /catalogs/feeds:
    get:
      x-ratelimit-category: catalogs_read
      summary: List feeds
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Fetch feeds owned by the "operating user_account".
      operationId: feeds/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
    post:
      x-ratelimit-category: catalogs_write
      summary: Create feed
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Create a new feed owned by the "operating user_account".
      operationId: feeds/create
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      tags:
      - catalogs
  /catalogs/feeds/{feed_id}:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get feed
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Get a single feed owned by the "operating user_account".
      operationId: feeds/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
    patch:
      x-ratelimit-category: catalogs_write
      summary: Update feed
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Update a feed owned by the "operating user_account".
      operationId: feeds/update
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      tags:
      - catalogs
    delete:
      x-ratelimit-category: catalogs_write
      summary: Delete feed
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Delete a feed owned by the "operating user_account".
      operationId: feeds/delete
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      tags:
      - catalogs
  /catalogs/feeds/{feed_id}/processing_results:
    get:
      x-ratelimit-category: catalogs_read
      summary: List processing results for a given feed
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Fetch a feed processing results owned by the owner user account. Please note that for now the bookmark parameter is not functional and only the first page will be available until it is implemented in some release in the near future.
      operationId: feed_processing_results/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
  /catalogs/processing_results/{processing_result_id}/item_issues:
    get:
      x-ratelimit-category: catalogs_read
      summary: List item issues for a given processing result
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        List item validation issues for a given feed processing result. Please note that for now query parameters 'item_numbers' and 'item_validation_issue' cannot be used simultaneously until it is implemented in some release in the future.
      operationId: items_issues/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
  /catalogs/items:
    get:
      summary: Get catalogs items
      description: Get the items of the catalog created by the "operating user_account".
        <a href="/docs/features/catalog-management/#Using%20batch%20updates%20for%20catalog%20management"
        target="_blank">See detailed documentation here.</a>
      operationId: items/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      tags:
      - catalogs
  /catalogs/items/batch/{batch_id}:
    get:
      summary: Get catalogs items batch
      description: Get a single catalogs items batch created by the "operating user_account".
        <a href="/docs/features/catalog-management/#Using%20batch%20updates%20for%20catalog%20management"
        target="_blank">See detailed documentation here.</a>
      operationId: items_batch/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      x-ratelimit-category: catalogs_read
      tags:
      - catalogs
  /catalogs/items/batch:
    post:
      summary: Perform an operation on an item batch
      description: This endpoint supports multiple operations on a set of one or more
        catalog items. <a href="/docs/features/catalog-management/#Using%20batch%20updates%20for%20catalog%20management"
        target="_blank">See detailed documentation here.</a>
      operationId: items_batch/post
      x-ratelimit-category: catalogs_write
      security:
      - pinterest_oauth2:
        - catalogs:read
        - catalogs:write
      tags:
      - catalogs
  /catalogs/products/get_by_product_group_filters:
    post:
      x-ratelimit-category: catalogs_read
      summary: List products that meet the criteria of the filter you provide.
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>
        List products Pins that meet the criteria specified in the Catalogs Product Group Filter given in the request.
        Note: This endpoint has been implemented in POST to allow for complex filters. This specific POST endpoint is designed to be idempotent.
      operationId: products_by_product_group_filter/list
      security:
      - pinterest_oauth2:
        - boards:read
        - catalogs:read
        - pins:read
      tags:
      - catalogs
  /catalogs/product_groups/{product_group_id}:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get a product group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Get a singe product group for a given Catalogs Product Group Id.
      operationId: catalogs_product_groups/get
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
    delete:
      x-ratelimit-category: catalogs_write
      summary: Delete product group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Delete a product group from being in use in Catalogs.
      operationId: catalogs_product_groups/delete
      security:
      - pinterest_oauth2:
        - catalogs:write
      tags:
      - catalogs
    patch:
      x-ratelimit-category: catalogs_write
      summary: Update product group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Update product group to use in Catalogs.
      operationId: catalogs_product_groups/update
      security:
      - pinterest_oauth2:
        - catalogs:write
      tags:
      - catalogs
  /catalogs/product_groups/{product_group_id}/products:
    get:
      x-ratelimit-category: catalogs_read
      summary: List products for a given product group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Get a list of product pins for a given Catalogs Product Group Id.
      operationId: catalogs_product_group_pins/list
      security:
      - pinterest_oauth2:
        - boards:read
        - catalogs:read
        - pins:read
      tags:
      - catalogs
  /catalogs/product_groups/{product_group_id}/product_counts:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get product counts for a given product group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>
        Get a product counts for a given Catalogs Product Group.
      operationId: catalogs_product_groups/product_counts_get
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
  /catalogs/product_groups:
    get:
      x-ratelimit-category: catalogs_read
      summary: Get product groups list
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Get a list of product groups for a given Catalogs Feed Id.
      operationId: catalogs_product_groups/list
      security:
      - pinterest_oauth2:
        - catalogs:read
      tags:
      - catalogs
    post:
      x-ratelimit-category: catalogs_write
      summary: Create product group
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/catalog-management/'>Learn more</a>.</strong>

        Create product group to use in Catalogs.
      operationId: catalogs_product_groups/create
      security:
      - pinterest_oauth2:
        - catalogs:write
      tags:
      - catalogs
  /terms/related:
    get:
      summary: List related terms
      description: |-
        <strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/features/ads-management/'>Learn more</a>.</strong> <p/>
        Get a list of terms logically related to each input term. <p/>
        Example: the term 'workout' would list related terms like 'one song workout', 'yoga workout', 'workout motivation', etc.
      tags:
      - terms
      operationId: terms_related/list
      security:
      - pinterest_oauth2:
        - ads:read
      x-ratelimit-category: ads_read
components:
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups,
              campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts
    basic:
      type: http
      scheme: basic