{
  "openapi": "3.0.3",
  "info": {
    "version": "5.3.0",
    "title": "Pinterest REST API",
    "description": "Pinterest's REST API",
    "contact": {
      "name": "Pinterest, Inc.",
      "url": "https://developers.pinterest.com/",
      "email": "pinterest-api@pinterest.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://spdx.org/licenses/MIT"
    },
    "termsOfService": "https://developers.pinterest.com/terms/"
  },
  "servers": [
    {
      "url": "https://api.pinterest.com/v5"
    }
  ],
  "tags": [
    {
      "name": "ad_accounts",
      "description": "View analytical information about advertising.\n\nNote: If the current operation_user_account (defined by the access token)\nhas access to another user's Ad Accounts via\n<a href='/docs/api/v5/#tag/Understanding-business-access'>Pinterest Business Access</a>,\nyou can modify your request to use the current operation_user_account's\npermissions to those Ad Accounts by including the ad_account_id in the path\nparameters for the request (e.g. .../?ad_account_id=12345&...)."
    },
    {
      "name": "boards",
      "description": "View, create, update, or delete information about boards."
    },
    {
      "name": "catalogs",
      "description": "Manage information about shopping product catalogs and items."
    },
    {
      "name": "media",
      "description": "Register and manage media uploads."
    },
    {
      "name": "oauth",
      "description": "Generating and refreshing OAuth access tokens."
    },
    {
      "name": "pins",
      "description": "View, create, update, or delete information about Pins."
    },
    {
      "name": "user_account",
      "description": "Read-only information about user accounts associated with a given access token."
    }
  ],
  "paths": {
    "/oauth/token": {
      "post": {
        "summary": "Generate OAuth access token",
        "description": "Generate an OAuth access token by using an authorization code or a refresh token.\n\nSee <a href='/docs/api/v5/#tag/Authentication'>Authentication</a> for more.",
        "tags": [
          "oauth"
        ],
        "operationId": "oauth/token",
        "security": [
          {}
        ],
        "x-ratelimit-category": "org_read"
      }
    },
    "/user_account": {
      "get": {
        "summary": "Get user account",
        "description": "Get account information for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nIf using Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\". See <a href='/docs/api/v5/#tag/Understanding-business-access'>Understanding Business Access</a> for more information.",
        "tags": [
          "user_account"
        ],
        "operationId": "user_account/get",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      }
    },
    "/user_account/analytics": {
      "get": {
        "summary": "Get user account analytics",
        "description": "Get analytics for the \"operation user_account\"\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an ad_account_id to use the owner of that ad_account as the \"operation user_account\".",
        "tags": [
          "user_account"
        ],
        "operationId": "user_account/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "user_accounts:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_analytics"
      }
    },
    "/pins": {
      "post": {
        "summary": "Create Pin",
        "description": "Create a Pin on a board or board section owned by the \"operation user_account\".\n\nNote: If the current \"operation user_account\" (defined by the access token) has access to another user's Ad Accounts via Pinterest Business Access, you can modify your request to make use of the current operation_user_account's permissions to those Ad Accounts by including the ad_account_id in the path parameters for the request (e.g. .../?ad_account_id=12345&...).\n\n- This function is[...]",
        "tags": [
          "pins"
        ],
        "operationId": "pins/create",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/pins/{pin_id}": {
      "get": {
        "summary": "Get Pin",
        "description": "Get a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href='/docs/api/v5/#operation/ad_accounts/list'>List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do this, the token user_account must have one of the [...]",
        "tags": [
          "pins"
        ],
        "operationId": "pins/get",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      },
      "delete": {
        "summary": "Delete Pin",
        "description": "Delete a Pins owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "pins"
        ],
        "operationId": "pins/delete",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write",
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/pins/{pin_id}/analytics": {
      "get": {
        "summary": "Get Pin analytics",
        "description": "Get analytics for a Pin owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.\n\nOptional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=\"https://developers.pinterest.com/docs/api/v5/#operation/ad_accounts/list\">List ad accounts</a>) to use the owner of that ad_account as the \"operation user_account\". In order to do th[...]",
        "tags": [
          "pins"
        ],
        "operationId": "pins/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_analytics"
      }
    },
    "/boards": {
      "get": {
        "summary": "List boards",
        "description": "Get a list of the boards owned by the \"operation user_account\" + group boards where this account is a collaborator\n\nOptional: Specify a privacy type (public, protected, or secret) to indicate which boards to return.\n- If no privacy is specified, all boards that can be returned (based on the scopes of the token and ad_account role if applicable) will be returned.",
        "tags": [
          "boards"
        ],
        "operationId": "boards/list",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      },
      "post": {
        "summary": "Create board",
        "description": "Create a board owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "boards/create",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/boards/{board_id}": {
      "get": {
        "summary": "Get board",
        "description": "Get a board owned by the operation user_account - or a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "boards/get",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      },
      "patch": {
        "summary": "Update board",
        "description": "Update a board owned by the \"operating user_account\".",
        "tags": [
          "boards"
        ],
        "operationId": "boards/update",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      },
      "delete": {
        "summary": "Delete board",
        "description": "Delete a board owned by the \"operation user_account\".\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "boards/delete",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/boards/{board_id}/sections": {
      "get": {
        "summary": "List board sections",
        "description": "Get a list of all board sections from a board owned by the \"operation user_account\" - or a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "board_sections/list",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      },
      "post": {
        "summary": "Create board section",
        "description": "Create a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "board_sections/create",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/boards/{board_id}/sections/{section_id}": {
      "patch": {
        "summary": "Update board section",
        "description": "Update a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "board_sections/update",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      },
      "delete": {
        "summary": "Delete board section",
        "description": "Delete a board section on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "board_sections/delete",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "boards:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/boards/{board_id}/sections/{section_id}/pins": {
      "get": {
        "summary": "List Pins on board section",
        "description": "Get a list of the Pins on a board section of a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "board_sections/list_pins",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      }
    },
    "/boards/{board_id}/pins": {
      "get": {
        "summary": "List Pins on board",
        "description": "Get a list of the Pins on a board owned by the \"operation user_account\" - or on a group board that has been shared with this account.\n- By default, the \"operation user_account\" is the token user_account.",
        "tags": [
          "boards"
        ],
        "operationId": "boards/list_pins",
        "security": [
          {
            "pinterest_oauth2": [
              "boards:read",
              "pins:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      }
    },
    "/media": {
      "get": {
        "summary": "List media uploads",
        "description": "List media uploads filtered by given parameters.\n\n<strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.",
        "tags": [
          "media"
        ],
        "operationId": "media/list",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      },
      "post": {
        "summary": "Register media upload",
        "description": "Register your intent to upload media\n\nThe response includes all of the information needed to upload the media\nto Pinterest.\n\nTo upload the media, make an HTTP POST request (using <tt>curl</tt>, for\nexample) to <tt>upload_url</tt> using the <tt>Content-Type</tt> header\nvalue. Send the media file's contents as the request's <tt>file</tt>\nparameter and also include all of the parameters from\n<tt>upload_parameters</tt>.\n\n<strong><a href='/docs/solutions/content-app[...]",
        "tags": [
          "media"
        ],
        "operationId": "media/create",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read",
              "pins:write"
            ]
          }
        ],
        "x-ratelimit-category": "org_write"
      }
    },
    "/media/{media_id}": {
      "get": {
        "summary": "Get media upload details",
        "description": "Get details for a registered media upload, including its current status.\n\n<strong><a href='/docs/solutions/content-apps/#creatingvideopins'>Learn more</a></strong> about video Pin creation.",
        "tags": [
          "media"
        ],
        "operationId": "media/get",
        "security": [
          {
            "pinterest_oauth2": [
              "pins:read"
            ]
          }
        ],
        "x-ratelimit-category": "org_read"
      }
    },
    "/ad_accounts": {
      "get": {
        "summary": "List ad accounts",
        "description": "Get a list of the ad_accounts that the \"operation user_account\" has access to.\n- This includes ad_accounts they own and ad_accounts that are owned by others who have granted them <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>.",
        "tags": [
          "ad_accounts"
        ],
        "operationId": "ad_accounts/list",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_read"
      }
    },
    "/ad_accounts/{ad_account_id}/analytics": {
      "get": {
        "summary": "Get ad account analytics",
        "description": "Get analytics for the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "ad_account/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns": {
      "get": {
        "summary": "List campaigns",
        "description": "Get a list of the campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "campaigns/list",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_read",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/campaigns/analytics": {
      "get": {
        "summary": "Get campaign analytics",
        "description": "Get analytics for the specified campaigns in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "campaigns/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups": {
      "get": {
        "summary": "List ad groups",
        "description": "Get a list of the ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "ad_groups/list",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_read",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/ad_groups/analytics": {
      "get": {
        "summary": "Get ad group analytics",
        "description": "Get analytics for the specified ad groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "ad_groups/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/ads": {
      "get": {
        "summary": "List ads",
        "description": "Get a list of the ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "ads/list",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_read",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/ads/analytics": {
      "get": {
        "summary": "Get ad analytics",
        "description": "Get analytics for the specified ads in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "ads/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/product_groups/analytics": {
      "get": {
        "summary": "Get product group analytics",
        "description": "Get analytics for the specified product groups in the specified <code>ad_account_id</code>, filtered by the specified options.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "product_groups/analytics",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/ad_accounts/{ad_account_id}/reports": {
      "get": {
        "summary": "Get the account analytics report created by the async call",
        "description": "This returns a URL to an analytics report given a token returned from the post request report creation call. You can use the URL to download the report and it's valid for an hour.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Business Access</a>: Admin, Analyst, Campaign Manager.",
        "operationId": "analytics/get_report",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      },
      "post": {
        "summary": "Create async request for an account analytics report",
        "description": "This returns a token that you can use to download the report when it is ready. Note that this endpoint requires the parameters to be passed as JSON-formatted in the request body. This endpoint does not support URL query parameters.\n- The token's user_account must either be the Owner of the specified ad account, or have one of the necessary roles granted to them via <a href=\"https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts\">Busi[...]",
        "operationId": "analytics/create_report",
        "security": [
          {
            "pinterest_oauth2": [
              "ads:read"
            ]
          }
        ],
        "x-ratelimit-category": "ads_analytics",
        "tags": [
          "ad_accounts"
        ]
      }
    },
    "/catalogs/feeds": {
      "get": {
        "x-ratelimit-category": "catalogs_read",
        "summary": "List feeds",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nFetch feeds owned by the \"operating user_account\".",
        "operationId": "feeds/list",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      },
      "post": {
        "x-ratelimit-category": "catalogs_write",
        "summary": "Create feed",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nCreate a new feed owned by the \"operating user_account\".",
        "operationId": "feeds/create",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      }
    },
    "/catalogs/feeds/{feed_id}": {
      "get": {
        "x-ratelimit-category": "catalogs_read",
        "summary": "Get feed",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nGet a single feed owned by the \"operating user_account\".",
        "operationId": "feeds/get",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      },
      "patch": {
        "x-ratelimit-category": "catalogs_write",
        "summary": "Update feed",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nUpdate a feed owned by the \"operating user_account\".",
        "operationId": "feeds/update",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      },
      "delete": {
        "x-ratelimit-category": "catalogs_write",
        "summary": "Delete feed",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nDelete a feed owned by the \"operating user_account\".",
        "operationId": "feeds/delete",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      }
    },
    "/catalogs/feeds/{feed_id}/processing_results": {
      "get": {
        "x-ratelimit-category": "catalogs_read",
        "summary": "List processing results for a given feed",
        "description": "<strong>This endpoint is currently in beta and not available to all apps. <a href='/docs/api/v5/#tag/Understanding-catalog-management'>Learn more</a>.</strong>\n\nFetch a feed processing results owned by the owner user account.",
        "operationId": "feed_processing_results/list",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      }
    },
    "/catalogs/items/batch/{batch_id}": {
      "get": {
        "summary": "Get catalogs items batch",
        "description": "Get a single catalogs items batch created by the \"operating user_account\"",
        "operationId": "items_batch/get",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "x-ratelimit-category": "catalogs_read",
        "tags": [
          "catalogs"
        ]
      }
    },
    "/catalogs/items/batch": {
      "post": {
        "summary": "Perform an operation on an item batch",
        "description": "This endpoint supports multiple operations on a set of one or more catalog items",
        "operationId": "items_batch/post",
        "x-ratelimit-category": "catalogs_write",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read",
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      }
    },
    "/catalogs/product_groups/{product_group_id}": {
      "delete": {
        "x-ratelimit-category": "catalogs_write",
        "summary": "Delete product group",
        "description": "Delete a product group from being in use in Catalogs.",
        "operationId": "catalogs_product_groups/delete",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      },
      "patch": {
        "x-ratelimit-category": "catalogs_write",
        "summary": "Update product group",
        "description": "Update product group to use in Catalogs.",
        "operationId": "catalogs_product_groups/update",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      }
    },
    "/catalogs/product_groups": {
      "get": {
        "x-ratelimit-category": "catalogs_read",
        "summary": "Get product groups list",
        "description": "Get a list of product groups for a given Catalogs Feed Id.",
        "operationId": "catalogs_product_groups/list",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:read"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      },
      "post": {
        "x-ratelimit-category": "catalogs_write",
        "summary": "Create product group",
        "description": "Create product group to use in Catalogs.",
        "operationId": "catalogs_product_groups/create",
        "security": [
          {
            "pinterest_oauth2": [
              "catalogs:write"
            ]
          }
        ],
        "tags": [
          "catalogs"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "pinterest_oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://www.pinterest.com/oauth/",
            "tokenUrl": "https://api.pinterest.com/v5/oauth/token",
            "scopes": {
              "ads:read": "See all of your advertising data, including ads, ad groups, campaigns etc.",
              "ads:write": "Create, update, or delete ads, ad groups, campaigns etc.",
              "boards:read": "See your public boards, including group boards you join",
              "boards:read_secret": "See your secret boards",
              "boards:write": "Create, update, or delete your public boards",
              "boards:write_secret": "Create, update, or delete your secret boards",
              "catalogs:read": "See all of your catalogs data",
              "catalogs:write": "Create, update, or delete your catalogs data",
              "pins:read": "See your public Pins",
              "pins:read_secret": "See your secret Pins",
              "pins:write": "Create, update, or delete your public Pins",
              "pins:write_secret": "Create, update, or delete your secret Pins",
              "user_accounts:read": "See your user accounts"
            }
          }
        }
      },
      "basic": {
        "type": "http",
        "scheme": "basic"
      }
    }
  }
}
